// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package scallywag

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IssueEventAction int32

const (
	IssueEventAction_IEA_ASSIGNED     IssueEventAction = 1
	IssueEventAction_IEA_UNASSIGNED   IssueEventAction = 2
	IssueEventAction_IEA_LABELED      IssueEventAction = 3
	IssueEventAction_IEA_UNLABELED    IssueEventAction = 4
	IssueEventAction_IEA_OPENED       IssueEventAction = 5
	IssueEventAction_IEA_EDITED       IssueEventAction = 6
	IssueEventAction_IEA_MILESTONED   IssueEventAction = 7
	IssueEventAction_IEA_DEMILESTONED IssueEventAction = 8
	IssueEventAction_IEA_CLOSED       IssueEventAction = 9
	IssueEventAction_IEA_REOPENED     IssueEventAction = 10
)

var IssueEventAction_name = map[int32]string{
	1:  "IEA_ASSIGNED",
	2:  "IEA_UNASSIGNED",
	3:  "IEA_LABELED",
	4:  "IEA_UNLABELED",
	5:  "IEA_OPENED",
	6:  "IEA_EDITED",
	7:  "IEA_MILESTONED",
	8:  "IEA_DEMILESTONED",
	9:  "IEA_CLOSED",
	10: "IEA_REOPENED",
}
var IssueEventAction_value = map[string]int32{
	"IEA_ASSIGNED":     1,
	"IEA_UNASSIGNED":   2,
	"IEA_LABELED":      3,
	"IEA_UNLABELED":    4,
	"IEA_OPENED":       5,
	"IEA_EDITED":       6,
	"IEA_MILESTONED":   7,
	"IEA_DEMILESTONED": 8,
	"IEA_CLOSED":       9,
	"IEA_REOPENED":     10,
}

func (x IssueEventAction) Enum() *IssueEventAction {
	p := new(IssueEventAction)
	*p = x
	return p
}
func (x IssueEventAction) String() string {
	return proto.EnumName(IssueEventAction_name, int32(x))
}
func (x *IssueEventAction) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(IssueEventAction_value, data, "IssueEventAction")
	if err != nil {
		return err
	}
	*x = IssueEventAction(value)
	return nil
}
func (IssueEventAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{0}
}

type IssueCommentEventAction int32

const (
	IssueCommentEventAction_ICEA_CREATED IssueCommentEventAction = 1
	IssueCommentEventAction_ICEA_EDITED_ IssueCommentEventAction = 2
	IssueCommentEventAction_ICEA_DELETED IssueCommentEventAction = 3
)

var IssueCommentEventAction_name = map[int32]string{
	1: "ICEA_CREATED",
	2: "ICEA_EDITED_",
	3: "ICEA_DELETED",
}
var IssueCommentEventAction_value = map[string]int32{
	"ICEA_CREATED": 1,
	"ICEA_EDITED_": 2,
	"ICEA_DELETED": 3,
}

func (x IssueCommentEventAction) Enum() *IssueCommentEventAction {
	p := new(IssueCommentEventAction)
	*p = x
	return p
}
func (x IssueCommentEventAction) String() string {
	return proto.EnumName(IssueCommentEventAction_name, int32(x))
}
func (x *IssueCommentEventAction) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(IssueCommentEventAction_value, data, "IssueCommentEventAction")
	if err != nil {
		return err
	}
	*x = IssueCommentEventAction(value)
	return nil
}
func (IssueCommentEventAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{1}
}

type ReviewState int32

const (
	ReviewState_RS_APPROVED          ReviewState = 1
	ReviewState_RS_CHANGES_REQUESTED ReviewState = 2
	ReviewState_RS_COMMENTED         ReviewState = 3
	ReviewState_RS_DISMISSED         ReviewState = 4
	ReviewState_RS_PENDING           ReviewState = 5
)

var ReviewState_name = map[int32]string{
	1: "RS_APPROVED",
	2: "RS_CHANGES_REQUESTED",
	3: "RS_COMMENTED",
	4: "RS_DISMISSED",
	5: "RS_PENDING",
}
var ReviewState_value = map[string]int32{
	"RS_APPROVED":          1,
	"RS_CHANGES_REQUESTED": 2,
	"RS_COMMENTED":         3,
	"RS_DISMISSED":         4,
	"RS_PENDING":           5,
}

func (x ReviewState) Enum() *ReviewState {
	p := new(ReviewState)
	*p = x
	return p
}
func (x ReviewState) String() string {
	return proto.EnumName(ReviewState_name, int32(x))
}
func (x *ReviewState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ReviewState_value, data, "ReviewState")
	if err != nil {
		return err
	}
	*x = ReviewState(value)
	return nil
}
func (ReviewState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{2}
}

type ReviewCommentEventAction int32

const (
	ReviewCommentEventAction_RCEA_CREATED ReviewCommentEventAction = 1
	ReviewCommentEventAction_RCEA_EDITED_ ReviewCommentEventAction = 2
	ReviewCommentEventAction_RCEA_DELETED ReviewCommentEventAction = 3
)

var ReviewCommentEventAction_name = map[int32]string{
	1: "RCEA_CREATED",
	2: "RCEA_EDITED_",
	3: "RCEA_DELETED",
}
var ReviewCommentEventAction_value = map[string]int32{
	"RCEA_CREATED": 1,
	"RCEA_EDITED_": 2,
	"RCEA_DELETED": 3,
}

func (x ReviewCommentEventAction) Enum() *ReviewCommentEventAction {
	p := new(ReviewCommentEventAction)
	*p = x
	return p
}
func (x ReviewCommentEventAction) String() string {
	return proto.EnumName(ReviewCommentEventAction_name, int32(x))
}
func (x *ReviewCommentEventAction) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ReviewCommentEventAction_value, data, "ReviewCommentEventAction")
	if err != nil {
		return err
	}
	*x = ReviewCommentEventAction(value)
	return nil
}
func (ReviewCommentEventAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{3}
}

type ReviewAction int32

const (
	ReviewAction_RA_APPROVE         ReviewAction = 1
	ReviewAction_RA_REQUEST_CHANGES ReviewAction = 2
	ReviewAction_RA_COMMENT         ReviewAction = 3
)

var ReviewAction_name = map[int32]string{
	1: "RA_APPROVE",
	2: "RA_REQUEST_CHANGES",
	3: "RA_COMMENT",
}
var ReviewAction_value = map[string]int32{
	"RA_APPROVE":         1,
	"RA_REQUEST_CHANGES": 2,
	"RA_COMMENT":         3,
}

func (x ReviewAction) Enum() *ReviewAction {
	p := new(ReviewAction)
	*p = x
	return p
}
func (x ReviewAction) String() string {
	return proto.EnumName(ReviewAction_name, int32(x))
}
func (x *ReviewAction) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ReviewAction_value, data, "ReviewAction")
	if err != nil {
		return err
	}
	*x = ReviewAction(value)
	return nil
}
func (ReviewAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{4}
}

type Reaction struct {
	Content              *string  `protobuf:"bytes,1,req,name=content" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reaction) Reset()         { *m = Reaction{} }
func (m *Reaction) String() string { return proto.CompactTextString(m) }
func (*Reaction) ProtoMessage()    {}
func (*Reaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{0}
}
func (m *Reaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reaction.Unmarshal(m, b)
}
func (m *Reaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reaction.Marshal(b, m, deterministic)
}
func (dst *Reaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reaction.Merge(dst, src)
}
func (m *Reaction) XXX_Size() int {
	return xxx_messageInfo_Reaction.Size(m)
}
func (m *Reaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Reaction.DiscardUnknown(m)
}

var xxx_messageInfo_Reaction proto.InternalMessageInfo

func (m *Reaction) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

type Status struct {
	State                *string  `protobuf:"bytes,1,req,name=state" json:"state,omitempty"`
	TargetState          *string  `protobuf:"bytes,2,opt,name=targetState" json:"targetState,omitempty"`
	Description          *string  `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Context              *string  `protobuf:"bytes,4,opt,name=context" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{1}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (dst *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(dst, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetState() string {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ""
}

func (m *Status) GetTargetState() string {
	if m != nil && m.TargetState != nil {
		return *m.TargetState
	}
	return ""
}

func (m *Status) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *Status) GetContext() string {
	if m != nil && m.Context != nil {
		return *m.Context
	}
	return ""
}

type CombinedStatus struct {
	Sha                  *string   `protobuf:"bytes,1,req,name=sha" json:"sha,omitempty"`
	Statuses             []*Status `protobuf:"bytes,2,rep,name=statuses" json:"statuses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CombinedStatus) Reset()         { *m = CombinedStatus{} }
func (m *CombinedStatus) String() string { return proto.CompactTextString(m) }
func (*CombinedStatus) ProtoMessage()    {}
func (*CombinedStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{2}
}
func (m *CombinedStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CombinedStatus.Unmarshal(m, b)
}
func (m *CombinedStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CombinedStatus.Marshal(b, m, deterministic)
}
func (dst *CombinedStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CombinedStatus.Merge(dst, src)
}
func (m *CombinedStatus) XXX_Size() int {
	return xxx_messageInfo_CombinedStatus.Size(m)
}
func (m *CombinedStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_CombinedStatus.DiscardUnknown(m)
}

var xxx_messageInfo_CombinedStatus proto.InternalMessageInfo

func (m *CombinedStatus) GetSha() string {
	if m != nil && m.Sha != nil {
		return *m.Sha
	}
	return ""
}

func (m *CombinedStatus) GetStatuses() []*Status {
	if m != nil {
		return m.Statuses
	}
	return nil
}

type User struct {
	Login                *string  `protobuf:"bytes,1,req,name=login" json:"login,omitempty"`
	Name                 *string  `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Email                *string  `protobuf:"bytes,3,req,name=email" json:"email,omitempty"`
	ID                   *uint64  `protobuf:"varint,4,req,name=ID" json:"ID,omitempty"`
	HTMLURL              *string  `protobuf:"bytes,5,req,name=HTMLURL" json:"HTMLURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{3}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetLogin() string {
	if m != nil && m.Login != nil {
		return *m.Login
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *User) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *User) GetHTMLURL() string {
	if m != nil && m.HTMLURL != nil {
		return *m.HTMLURL
	}
	return ""
}

type Repo struct {
	Owner                *User    `protobuf:"bytes,1,req,name=owner" json:"owner,omitempty"`
	Name                 *string  `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	FullName             *string  `protobuf:"bytes,3,req,name=fullName" json:"fullName,omitempty"`
	HTMLURL              *string  `protobuf:"bytes,4,req,name=HTMLURL" json:"HTMLURL,omitempty"`
	Fork                 *bool    `protobuf:"varint,5,req,name=fork" json:"fork,omitempty"`
	DefaultBranch        *string  `protobuf:"bytes,6,req,name=defaultBranch" json:"defaultBranch,omitempty"`
	Archived             *bool    `protobuf:"varint,7,req,name=archived" json:"archived,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Repo) Reset()         { *m = Repo{} }
func (m *Repo) String() string { return proto.CompactTextString(m) }
func (*Repo) ProtoMessage()    {}
func (*Repo) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{4}
}
func (m *Repo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repo.Unmarshal(m, b)
}
func (m *Repo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repo.Marshal(b, m, deterministic)
}
func (dst *Repo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repo.Merge(dst, src)
}
func (m *Repo) XXX_Size() int {
	return xxx_messageInfo_Repo.Size(m)
}
func (m *Repo) XXX_DiscardUnknown() {
	xxx_messageInfo_Repo.DiscardUnknown(m)
}

var xxx_messageInfo_Repo proto.InternalMessageInfo

func (m *Repo) GetOwner() *User {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Repo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Repo) GetFullName() string {
	if m != nil && m.FullName != nil {
		return *m.FullName
	}
	return ""
}

func (m *Repo) GetHTMLURL() string {
	if m != nil && m.HTMLURL != nil {
		return *m.HTMLURL
	}
	return ""
}

func (m *Repo) GetFork() bool {
	if m != nil && m.Fork != nil {
		return *m.Fork
	}
	return false
}

func (m *Repo) GetDefaultBranch() string {
	if m != nil && m.DefaultBranch != nil {
		return *m.DefaultBranch
	}
	return ""
}

func (m *Repo) GetArchived() bool {
	if m != nil && m.Archived != nil {
		return *m.Archived
	}
	return false
}

type Branch struct {
	Name                 *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Protected            *bool    `protobuf:"varint,2,req,name=protected" json:"protected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Branch) Reset()         { *m = Branch{} }
func (m *Branch) String() string { return proto.CompactTextString(m) }
func (*Branch) ProtoMessage()    {}
func (*Branch) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{5}
}
func (m *Branch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Branch.Unmarshal(m, b)
}
func (m *Branch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Branch.Marshal(b, m, deterministic)
}
func (dst *Branch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Branch.Merge(dst, src)
}
func (m *Branch) XXX_Size() int {
	return xxx_messageInfo_Branch.Size(m)
}
func (m *Branch) XXX_DiscardUnknown() {
	xxx_messageInfo_Branch.DiscardUnknown(m)
}

var xxx_messageInfo_Branch proto.InternalMessageInfo

func (m *Branch) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Branch) GetProtected() bool {
	if m != nil && m.Protected != nil {
		return *m.Protected
	}
	return false
}

type HookConfig struct {
	URL                  *string  `protobuf:"bytes,1,req,name=URL" json:"URL,omitempty"`
	ContentType          *string  `protobuf:"bytes,2,opt,name=contentType" json:"contentType,omitempty"`
	Secret               *string  `protobuf:"bytes,3,opt,name=secret" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HookConfig) Reset()         { *m = HookConfig{} }
func (m *HookConfig) String() string { return proto.CompactTextString(m) }
func (*HookConfig) ProtoMessage()    {}
func (*HookConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{6}
}
func (m *HookConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HookConfig.Unmarshal(m, b)
}
func (m *HookConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HookConfig.Marshal(b, m, deterministic)
}
func (dst *HookConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HookConfig.Merge(dst, src)
}
func (m *HookConfig) XXX_Size() int {
	return xxx_messageInfo_HookConfig.Size(m)
}
func (m *HookConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_HookConfig.DiscardUnknown(m)
}

var xxx_messageInfo_HookConfig proto.InternalMessageInfo

func (m *HookConfig) GetURL() string {
	if m != nil && m.URL != nil {
		return *m.URL
	}
	return ""
}

func (m *HookConfig) GetContentType() string {
	if m != nil && m.ContentType != nil {
		return *m.ContentType
	}
	return ""
}

func (m *HookConfig) GetSecret() string {
	if m != nil && m.Secret != nil {
		return *m.Secret
	}
	return ""
}

type Hook struct {
	ID                   *uint64     `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	Name                 *string     `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Events               []string    `protobuf:"bytes,3,rep,name=events" json:"events,omitempty"`
	Active               *bool       `protobuf:"varint,4,req,name=active" json:"active,omitempty"`
	Config               *HookConfig `protobuf:"bytes,5,req,name=config" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Hook) Reset()         { *m = Hook{} }
func (m *Hook) String() string { return proto.CompactTextString(m) }
func (*Hook) ProtoMessage()    {}
func (*Hook) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{7}
}
func (m *Hook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hook.Unmarshal(m, b)
}
func (m *Hook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hook.Marshal(b, m, deterministic)
}
func (dst *Hook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hook.Merge(dst, src)
}
func (m *Hook) XXX_Size() int {
	return xxx_messageInfo_Hook.Size(m)
}
func (m *Hook) XXX_DiscardUnknown() {
	xxx_messageInfo_Hook.DiscardUnknown(m)
}

var xxx_messageInfo_Hook proto.InternalMessageInfo

func (m *Hook) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *Hook) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Hook) GetEvents() []string {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *Hook) GetActive() bool {
	if m != nil && m.Active != nil {
		return *m.Active
	}
	return false
}

func (m *Hook) GetConfig() *HookConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type HookRequest struct {
	Name                 *string     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Active               *bool       `protobuf:"varint,2,opt,name=active" json:"active,omitempty"`
	AddEvents            []string    `protobuf:"bytes,3,rep,name=addEvents" json:"addEvents,omitempty"`
	Config               *HookConfig `protobuf:"bytes,4,opt,name=config" json:"config,omitempty"`
	Events               []string    `protobuf:"bytes,5,rep,name=events" json:"events,omitempty"`
	RemoveEvents         []string    `protobuf:"bytes,6,rep,name=removeEvents" json:"removeEvents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *HookRequest) Reset()         { *m = HookRequest{} }
func (m *HookRequest) String() string { return proto.CompactTextString(m) }
func (*HookRequest) ProtoMessage()    {}
func (*HookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{8}
}
func (m *HookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HookRequest.Unmarshal(m, b)
}
func (m *HookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HookRequest.Marshal(b, m, deterministic)
}
func (dst *HookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HookRequest.Merge(dst, src)
}
func (m *HookRequest) XXX_Size() int {
	return xxx_messageInfo_HookRequest.Size(m)
}
func (m *HookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HookRequest proto.InternalMessageInfo

func (m *HookRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *HookRequest) GetActive() bool {
	if m != nil && m.Active != nil {
		return *m.Active
	}
	return false
}

func (m *HookRequest) GetAddEvents() []string {
	if m != nil {
		return m.AddEvents
	}
	return nil
}

func (m *HookRequest) GetConfig() *HookConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *HookRequest) GetEvents() []string {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *HookRequest) GetRemoveEvents() []string {
	if m != nil {
		return m.RemoveEvents
	}
	return nil
}

type Milestone struct {
	Title                *string  `protobuf:"bytes,1,req,name=title" json:"title,omitempty"`
	Number               *uint64  `protobuf:"varint,2,req,name=number" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Milestone) Reset()         { *m = Milestone{} }
func (m *Milestone) String() string { return proto.CompactTextString(m) }
func (*Milestone) ProtoMessage()    {}
func (*Milestone) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{9}
}
func (m *Milestone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Milestone.Unmarshal(m, b)
}
func (m *Milestone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Milestone.Marshal(b, m, deterministic)
}
func (dst *Milestone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Milestone.Merge(dst, src)
}
func (m *Milestone) XXX_Size() int {
	return xxx_messageInfo_Milestone.Size(m)
}
func (m *Milestone) XXX_DiscardUnknown() {
	xxx_messageInfo_Milestone.DiscardUnknown(m)
}

var xxx_messageInfo_Milestone proto.InternalMessageInfo

func (m *Milestone) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Milestone) GetNumber() uint64 {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return 0
}

type Label struct {
	URL                  *string  `protobuf:"bytes,1,req,name=URL" json:"URL,omitempty"`
	Name                 *string  `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Description          *string  `protobuf:"bytes,3,req,name=description" json:"description,omitempty"`
	Color                *string  `protobuf:"bytes,4,req,name=color" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Label) Reset()         { *m = Label{} }
func (m *Label) String() string { return proto.CompactTextString(m) }
func (*Label) ProtoMessage()    {}
func (*Label) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{10}
}
func (m *Label) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Label.Unmarshal(m, b)
}
func (m *Label) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Label.Marshal(b, m, deterministic)
}
func (dst *Label) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Label.Merge(dst, src)
}
func (m *Label) XXX_Size() int {
	return xxx_messageInfo_Label.Size(m)
}
func (m *Label) XXX_DiscardUnknown() {
	xxx_messageInfo_Label.DiscardUnknown(m)
}

var xxx_messageInfo_Label proto.InternalMessageInfo

func (m *Label) GetURL() string {
	if m != nil && m.URL != nil {
		return *m.URL
	}
	return ""
}

func (m *Label) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Label) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *Label) GetColor() string {
	if m != nil && m.Color != nil {
		return *m.Color
	}
	return ""
}

type Issue struct {
	User                 *User      `protobuf:"bytes,1,req,name=user" json:"user,omitempty"`
	Number               *uint64    `protobuf:"varint,2,req,name=number" json:"number,omitempty"`
	Title                *string    `protobuf:"bytes,3,req,name=title" json:"title,omitempty"`
	State                *string    `protobuf:"bytes,4,req,name=state" json:"state,omitempty"`
	HTMLURL              *string    `protobuf:"bytes,5,req,name=HTMLURL" json:"HTMLURL,omitempty"`
	Labels               []*Label   `protobuf:"bytes,6,rep,name=labels" json:"labels,omitempty"`
	Assignees            []*User    `protobuf:"bytes,7,rep,name=assignees" json:"assignees,omitempty"`
	Body                 *string    `protobuf:"bytes,8,req,name=body" json:"body,omitempty"`
	CreatedAt            *string    `protobuf:"bytes,9,req,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt            *string    `protobuf:"bytes,10,req,name=updatedAt" json:"updatedAt,omitempty"`
	Milestone            *Milestone `protobuf:"bytes,11,req,name=milestone" json:"milestone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Issue) Reset()         { *m = Issue{} }
func (m *Issue) String() string { return proto.CompactTextString(m) }
func (*Issue) ProtoMessage()    {}
func (*Issue) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{11}
}
func (m *Issue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Issue.Unmarshal(m, b)
}
func (m *Issue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Issue.Marshal(b, m, deterministic)
}
func (dst *Issue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Issue.Merge(dst, src)
}
func (m *Issue) XXX_Size() int {
	return xxx_messageInfo_Issue.Size(m)
}
func (m *Issue) XXX_DiscardUnknown() {
	xxx_messageInfo_Issue.DiscardUnknown(m)
}

var xxx_messageInfo_Issue proto.InternalMessageInfo

func (m *Issue) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Issue) GetNumber() uint64 {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return 0
}

func (m *Issue) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Issue) GetState() string {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ""
}

func (m *Issue) GetHTMLURL() string {
	if m != nil && m.HTMLURL != nil {
		return *m.HTMLURL
	}
	return ""
}

func (m *Issue) GetLabels() []*Label {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Issue) GetAssignees() []*User {
	if m != nil {
		return m.Assignees
	}
	return nil
}

func (m *Issue) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func (m *Issue) GetCreatedAt() string {
	if m != nil && m.CreatedAt != nil {
		return *m.CreatedAt
	}
	return ""
}

func (m *Issue) GetUpdatedAt() string {
	if m != nil && m.UpdatedAt != nil {
		return *m.UpdatedAt
	}
	return ""
}

func (m *Issue) GetMilestone() *Milestone {
	if m != nil {
		return m.Milestone
	}
	return nil
}

type IssueComment struct {
	ID                   *string  `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Body                 *string  `protobuf:"bytes,2,req,name=body" json:"body,omitempty"`
	User                 *User    `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
	HTMLURL              *string  `protobuf:"bytes,4,opt,name=HTMLURL" json:"HTMLURL,omitempty"`
	CreatedAt            *string  `protobuf:"bytes,5,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt            *string  `protobuf:"bytes,6,opt,name=updatedAt" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssueComment) Reset()         { *m = IssueComment{} }
func (m *IssueComment) String() string { return proto.CompactTextString(m) }
func (*IssueComment) ProtoMessage()    {}
func (*IssueComment) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{12}
}
func (m *IssueComment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueComment.Unmarshal(m, b)
}
func (m *IssueComment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueComment.Marshal(b, m, deterministic)
}
func (dst *IssueComment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueComment.Merge(dst, src)
}
func (m *IssueComment) XXX_Size() int {
	return xxx_messageInfo_IssueComment.Size(m)
}
func (m *IssueComment) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueComment.DiscardUnknown(m)
}

var xxx_messageInfo_IssueComment proto.InternalMessageInfo

func (m *IssueComment) GetID() string {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return ""
}

func (m *IssueComment) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func (m *IssueComment) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *IssueComment) GetHTMLURL() string {
	if m != nil && m.HTMLURL != nil {
		return *m.HTMLURL
	}
	return ""
}

func (m *IssueComment) GetCreatedAt() string {
	if m != nil && m.CreatedAt != nil {
		return *m.CreatedAt
	}
	return ""
}

func (m *IssueComment) GetUpdatedAt() string {
	if m != nil && m.UpdatedAt != nil {
		return *m.UpdatedAt
	}
	return ""
}

type IssueSearchResult struct {
	Total                *uint64  `protobuf:"varint,1,opt,name=total" json:"total,omitempty"`
	Issues               []*Issue `protobuf:"bytes,2,rep,name=issues" json:"issues,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssueSearchResult) Reset()         { *m = IssueSearchResult{} }
func (m *IssueSearchResult) String() string { return proto.CompactTextString(m) }
func (*IssueSearchResult) ProtoMessage()    {}
func (*IssueSearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{13}
}
func (m *IssueSearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueSearchResult.Unmarshal(m, b)
}
func (m *IssueSearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueSearchResult.Marshal(b, m, deterministic)
}
func (dst *IssueSearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueSearchResult.Merge(dst, src)
}
func (m *IssueSearchResult) XXX_Size() int {
	return xxx_messageInfo_IssueSearchResult.Size(m)
}
func (m *IssueSearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueSearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_IssueSearchResult proto.InternalMessageInfo

func (m *IssueSearchResult) GetTotal() uint64 {
	if m != nil && m.Total != nil {
		return *m.Total
	}
	return 0
}

func (m *IssueSearchResult) GetIssues() []*Issue {
	if m != nil {
		return m.Issues
	}
	return nil
}

type IssueEvent struct {
	Action               *IssueEventAction `protobuf:"varint,1,req,name=action,enum=scallywag.IssueEventAction" json:"action,omitempty"`
	Issue                *Issue            `protobuf:"bytes,2,req,name=issue" json:"issue,omitempty"`
	Repo                 *Repo             `protobuf:"bytes,3,req,name=repo" json:"repo,omitempty"`
	Label                *Label            `protobuf:"bytes,4,req,name=label" json:"label,omitempty"`
	GUID                 *string           `protobuf:"bytes,5,req,name=GUID" json:"GUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *IssueEvent) Reset()         { *m = IssueEvent{} }
func (m *IssueEvent) String() string { return proto.CompactTextString(m) }
func (*IssueEvent) ProtoMessage()    {}
func (*IssueEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{14}
}
func (m *IssueEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueEvent.Unmarshal(m, b)
}
func (m *IssueEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueEvent.Marshal(b, m, deterministic)
}
func (dst *IssueEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueEvent.Merge(dst, src)
}
func (m *IssueEvent) XXX_Size() int {
	return xxx_messageInfo_IssueEvent.Size(m)
}
func (m *IssueEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueEvent.DiscardUnknown(m)
}

var xxx_messageInfo_IssueEvent proto.InternalMessageInfo

func (m *IssueEvent) GetAction() IssueEventAction {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return IssueEventAction_IEA_ASSIGNED
}

func (m *IssueEvent) GetIssue() *Issue {
	if m != nil {
		return m.Issue
	}
	return nil
}

func (m *IssueEvent) GetRepo() *Repo {
	if m != nil {
		return m.Repo
	}
	return nil
}

func (m *IssueEvent) GetLabel() *Label {
	if m != nil {
		return m.Label
	}
	return nil
}

func (m *IssueEvent) GetGUID() string {
	if m != nil && m.GUID != nil {
		return *m.GUID
	}
	return ""
}

type PullRequestBranch struct {
	Ref                  *string  `protobuf:"bytes,1,req,name=ref" json:"ref,omitempty"`
	SHA                  *string  `protobuf:"bytes,2,req,name=SHA" json:"SHA,omitempty"`
	Repo                 *Repo    `protobuf:"bytes,3,req,name=repo" json:"repo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullRequestBranch) Reset()         { *m = PullRequestBranch{} }
func (m *PullRequestBranch) String() string { return proto.CompactTextString(m) }
func (*PullRequestBranch) ProtoMessage()    {}
func (*PullRequestBranch) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{15}
}
func (m *PullRequestBranch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRequestBranch.Unmarshal(m, b)
}
func (m *PullRequestBranch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRequestBranch.Marshal(b, m, deterministic)
}
func (dst *PullRequestBranch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRequestBranch.Merge(dst, src)
}
func (m *PullRequestBranch) XXX_Size() int {
	return xxx_messageInfo_PullRequestBranch.Size(m)
}
func (m *PullRequestBranch) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRequestBranch.DiscardUnknown(m)
}

var xxx_messageInfo_PullRequestBranch proto.InternalMessageInfo

func (m *PullRequestBranch) GetRef() string {
	if m != nil && m.Ref != nil {
		return *m.Ref
	}
	return ""
}

func (m *PullRequestBranch) GetSHA() string {
	if m != nil && m.SHA != nil {
		return *m.SHA
	}
	return ""
}

func (m *PullRequestBranch) GetRepo() *Repo {
	if m != nil {
		return m.Repo
	}
	return nil
}

type PullRequest struct {
	Number               *uint64            `protobuf:"varint,1,req,name=number" json:"number,omitempty"`
	HTMLURL              *string            `protobuf:"bytes,2,req,name=HTMLURL" json:"HTMLURL,omitempty"`
	User                 *User              `protobuf:"bytes,3,req,name=user" json:"user,omitempty"`
	Base                 *PullRequestBranch `protobuf:"bytes,4,req,name=base" json:"base,omitempty"`
	Head                 *PullRequestBranch `protobuf:"bytes,5,req,name=head" json:"head,omitempty"`
	Title                *string            `protobuf:"bytes,6,req,name=title" json:"title,omitempty"`
	Body                 *string            `protobuf:"bytes,7,req,name=body" json:"body,omitempty"`
	RequestedReviewers   []*User            `protobuf:"bytes,8,rep,name=requestedReviewers" json:"requestedReviewers,omitempty"`
	Assignees            []*User            `protobuf:"bytes,9,rep,name=assignees" json:"assignees,omitempty"`
	State                *string            `protobuf:"bytes,10,req,name=state" json:"state,omitempty"`
	Draft                *bool              `protobuf:"varint,11,req,name=draft" json:"draft,omitempty"`
	Merged               *bool              `protobuf:"varint,12,req,name=merged" json:"merged,omitempty"`
	CreatedAt            *string            `protobuf:"bytes,13,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt            *string            `protobuf:"bytes,14,opt,name=updatedAt" json:"updatedAt,omitempty"`
	MergeSHA             *string            `protobuf:"bytes,15,req,name=mergeSHA" json:"mergeSHA,omitempty"`
	Mergeable            *string            `protobuf:"bytes,16,opt,name=mergeable" json:"mergeable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PullRequest) Reset()         { *m = PullRequest{} }
func (m *PullRequest) String() string { return proto.CompactTextString(m) }
func (*PullRequest) ProtoMessage()    {}
func (*PullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{16}
}
func (m *PullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRequest.Unmarshal(m, b)
}
func (m *PullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRequest.Marshal(b, m, deterministic)
}
func (dst *PullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRequest.Merge(dst, src)
}
func (m *PullRequest) XXX_Size() int {
	return xxx_messageInfo_PullRequest.Size(m)
}
func (m *PullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullRequest proto.InternalMessageInfo

func (m *PullRequest) GetNumber() uint64 {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return 0
}

func (m *PullRequest) GetHTMLURL() string {
	if m != nil && m.HTMLURL != nil {
		return *m.HTMLURL
	}
	return ""
}

func (m *PullRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *PullRequest) GetBase() *PullRequestBranch {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *PullRequest) GetHead() *PullRequestBranch {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *PullRequest) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *PullRequest) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func (m *PullRequest) GetRequestedReviewers() []*User {
	if m != nil {
		return m.RequestedReviewers
	}
	return nil
}

func (m *PullRequest) GetAssignees() []*User {
	if m != nil {
		return m.Assignees
	}
	return nil
}

func (m *PullRequest) GetState() string {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ""
}

func (m *PullRequest) GetDraft() bool {
	if m != nil && m.Draft != nil {
		return *m.Draft
	}
	return false
}

func (m *PullRequest) GetMerged() bool {
	if m != nil && m.Merged != nil {
		return *m.Merged
	}
	return false
}

func (m *PullRequest) GetCreatedAt() string {
	if m != nil && m.CreatedAt != nil {
		return *m.CreatedAt
	}
	return ""
}

func (m *PullRequest) GetUpdatedAt() string {
	if m != nil && m.UpdatedAt != nil {
		return *m.UpdatedAt
	}
	return ""
}

func (m *PullRequest) GetMergeSHA() string {
	if m != nil && m.MergeSHA != nil {
		return *m.MergeSHA
	}
	return ""
}

func (m *PullRequest) GetMergeable() string {
	if m != nil && m.Mergeable != nil {
		return *m.Mergeable
	}
	return ""
}

type Commit struct {
	ID                   *string  `protobuf:"bytes,1,req,name=ID" json:"ID,omitempty"`
	Message              *string  `protobuf:"bytes,2,req,name=message" json:"message,omitempty"`
	Added                []string `protobuf:"bytes,3,rep,name=added" json:"added,omitempty"`
	Removed              []string `protobuf:"bytes,4,rep,name=removed" json:"removed,omitempty"`
	Modified             []string `protobuf:"bytes,5,rep,name=modified" json:"modified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{17}
}
func (m *Commit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit.Unmarshal(m, b)
}
func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit.Marshal(b, m, deterministic)
}
func (dst *Commit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit.Merge(dst, src)
}
func (m *Commit) XXX_Size() int {
	return xxx_messageInfo_Commit.Size(m)
}
func (m *Commit) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit.DiscardUnknown(m)
}

var xxx_messageInfo_Commit proto.InternalMessageInfo

func (m *Commit) GetID() string {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return ""
}

func (m *Commit) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *Commit) GetAdded() []string {
	if m != nil {
		return m.Added
	}
	return nil
}

func (m *Commit) GetRemoved() []string {
	if m != nil {
		return m.Removed
	}
	return nil
}

func (m *Commit) GetModified() []string {
	if m != nil {
		return m.Modified
	}
	return nil
}

type PushEvent struct {
	Ref                  *string   `protobuf:"bytes,1,req,name=ref" json:"ref,omitempty"`
	Before               *string   `protobuf:"bytes,2,req,name=before" json:"before,omitempty"`
	After                *string   `protobuf:"bytes,3,req,name=after" json:"after,omitempty"`
	Created              *bool     `protobuf:"varint,4,req,name=created" json:"created,omitempty"`
	Deleted              *bool     `protobuf:"varint,5,req,name=deleted" json:"deleted,omitempty"`
	Forced               *bool     `protobuf:"varint,6,req,name=forced" json:"forced,omitempty"`
	Compare              *string   `protobuf:"bytes,7,req,name=compare" json:"compare,omitempty"`
	Commits              []*Commit `protobuf:"bytes,8,rep,name=commits" json:"commits,omitempty"`
	Pusher               *User     `protobuf:"bytes,9,req,name=pusher" json:"pusher,omitempty"`
	Sender               *User     `protobuf:"bytes,10,req,name=sender" json:"sender,omitempty"`
	Repo                 *Repo     `protobuf:"bytes,11,req,name=repo" json:"repo,omitempty"`
	GUID                 *string   `protobuf:"bytes,12,req,name=GUID" json:"GUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PushEvent) Reset()         { *m = PushEvent{} }
func (m *PushEvent) String() string { return proto.CompactTextString(m) }
func (*PushEvent) ProtoMessage()    {}
func (*PushEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{18}
}
func (m *PushEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushEvent.Unmarshal(m, b)
}
func (m *PushEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushEvent.Marshal(b, m, deterministic)
}
func (dst *PushEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushEvent.Merge(dst, src)
}
func (m *PushEvent) XXX_Size() int {
	return xxx_messageInfo_PushEvent.Size(m)
}
func (m *PushEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PushEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PushEvent proto.InternalMessageInfo

func (m *PushEvent) GetRef() string {
	if m != nil && m.Ref != nil {
		return *m.Ref
	}
	return ""
}

func (m *PushEvent) GetBefore() string {
	if m != nil && m.Before != nil {
		return *m.Before
	}
	return ""
}

func (m *PushEvent) GetAfter() string {
	if m != nil && m.After != nil {
		return *m.After
	}
	return ""
}

func (m *PushEvent) GetCreated() bool {
	if m != nil && m.Created != nil {
		return *m.Created
	}
	return false
}

func (m *PushEvent) GetDeleted() bool {
	if m != nil && m.Deleted != nil {
		return *m.Deleted
	}
	return false
}

func (m *PushEvent) GetForced() bool {
	if m != nil && m.Forced != nil {
		return *m.Forced
	}
	return false
}

func (m *PushEvent) GetCompare() string {
	if m != nil && m.Compare != nil {
		return *m.Compare
	}
	return ""
}

func (m *PushEvent) GetCommits() []*Commit {
	if m != nil {
		return m.Commits
	}
	return nil
}

func (m *PushEvent) GetPusher() *User {
	if m != nil {
		return m.Pusher
	}
	return nil
}

func (m *PushEvent) GetSender() *User {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *PushEvent) GetRepo() *Repo {
	if m != nil {
		return m.Repo
	}
	return nil
}

func (m *PushEvent) GetGUID() string {
	if m != nil && m.GUID != nil {
		return *m.GUID
	}
	return ""
}

type StatusEvent struct {
	SHA                  *string  `protobuf:"bytes,1,opt,name=SHA" json:"SHA,omitempty"`
	State                *string  `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	Description          *string  `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	TargetURL            *string  `protobuf:"bytes,4,opt,name=targetURL" json:"targetURL,omitempty"`
	ID                   *uint64  `protobuf:"varint,5,opt,name=ID" json:"ID,omitempty"`
	Name                 *string  `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	Context              *string  `protobuf:"bytes,7,opt,name=context" json:"context,omitempty"`
	Sender               *User    `protobuf:"bytes,8,opt,name=sender" json:"sender,omitempty"`
	Repo                 *Repo    `protobuf:"bytes,9,opt,name=repo" json:"repo,omitempty"`
	GUID                 *string  `protobuf:"bytes,10,req,name=GUID" json:"GUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusEvent) Reset()         { *m = StatusEvent{} }
func (m *StatusEvent) String() string { return proto.CompactTextString(m) }
func (*StatusEvent) ProtoMessage()    {}
func (*StatusEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{19}
}
func (m *StatusEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusEvent.Unmarshal(m, b)
}
func (m *StatusEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusEvent.Marshal(b, m, deterministic)
}
func (dst *StatusEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusEvent.Merge(dst, src)
}
func (m *StatusEvent) XXX_Size() int {
	return xxx_messageInfo_StatusEvent.Size(m)
}
func (m *StatusEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusEvent.DiscardUnknown(m)
}

var xxx_messageInfo_StatusEvent proto.InternalMessageInfo

func (m *StatusEvent) GetSHA() string {
	if m != nil && m.SHA != nil {
		return *m.SHA
	}
	return ""
}

func (m *StatusEvent) GetState() string {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ""
}

func (m *StatusEvent) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *StatusEvent) GetTargetURL() string {
	if m != nil && m.TargetURL != nil {
		return *m.TargetURL
	}
	return ""
}

func (m *StatusEvent) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *StatusEvent) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *StatusEvent) GetContext() string {
	if m != nil && m.Context != nil {
		return *m.Context
	}
	return ""
}

func (m *StatusEvent) GetSender() *User {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *StatusEvent) GetRepo() *Repo {
	if m != nil {
		return m.Repo
	}
	return nil
}

func (m *StatusEvent) GetGUID() string {
	if m != nil && m.GUID != nil {
		return *m.GUID
	}
	return ""
}

type Review struct {
	ID                   *uint64      `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	User                 *User        `protobuf:"bytes,2,req,name=user" json:"user,omitempty"`
	Body                 *string      `protobuf:"bytes,3,req,name=body" json:"body,omitempty"`
	State                *ReviewState `protobuf:"varint,4,req,name=state,enum=scallywag.ReviewState" json:"state,omitempty"`
	HTMLURL              *string      `protobuf:"bytes,5,req,name=HTMLURL" json:"HTMLURL,omitempty"`
	SubmittedAt          *string      `protobuf:"bytes,6,req,name=submittedAt" json:"submittedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Review) Reset()         { *m = Review{} }
func (m *Review) String() string { return proto.CompactTextString(m) }
func (*Review) ProtoMessage()    {}
func (*Review) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{20}
}
func (m *Review) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Review.Unmarshal(m, b)
}
func (m *Review) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Review.Marshal(b, m, deterministic)
}
func (dst *Review) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Review.Merge(dst, src)
}
func (m *Review) XXX_Size() int {
	return xxx_messageInfo_Review.Size(m)
}
func (m *Review) XXX_DiscardUnknown() {
	xxx_messageInfo_Review.DiscardUnknown(m)
}

var xxx_messageInfo_Review proto.InternalMessageInfo

func (m *Review) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *Review) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Review) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func (m *Review) GetState() ReviewState {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ReviewState_RS_APPROVED
}

func (m *Review) GetHTMLURL() string {
	if m != nil && m.HTMLURL != nil {
		return *m.HTMLURL
	}
	return ""
}

func (m *Review) GetSubmittedAt() string {
	if m != nil && m.SubmittedAt != nil {
		return *m.SubmittedAt
	}
	return ""
}

type ReviewEvent struct {
	Action               *string      `protobuf:"bytes,1,req,name=action" json:"action,omitempty"`
	PullRequest          *PullRequest `protobuf:"bytes,2,req,name=pullRequest" json:"pullRequest,omitempty"`
	Repo                 *Repo        `protobuf:"bytes,3,req,name=repo" json:"repo,omitempty"`
	Review               *Review      `protobuf:"bytes,4,req,name=review" json:"review,omitempty"`
	GUID                 *string      `protobuf:"bytes,5,req,name=GUID" json:"GUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReviewEvent) Reset()         { *m = ReviewEvent{} }
func (m *ReviewEvent) String() string { return proto.CompactTextString(m) }
func (*ReviewEvent) ProtoMessage()    {}
func (*ReviewEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{21}
}
func (m *ReviewEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReviewEvent.Unmarshal(m, b)
}
func (m *ReviewEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReviewEvent.Marshal(b, m, deterministic)
}
func (dst *ReviewEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReviewEvent.Merge(dst, src)
}
func (m *ReviewEvent) XXX_Size() int {
	return xxx_messageInfo_ReviewEvent.Size(m)
}
func (m *ReviewEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ReviewEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ReviewEvent proto.InternalMessageInfo

func (m *ReviewEvent) GetAction() string {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ""
}

func (m *ReviewEvent) GetPullRequest() *PullRequest {
	if m != nil {
		return m.PullRequest
	}
	return nil
}

func (m *ReviewEvent) GetRepo() *Repo {
	if m != nil {
		return m.Repo
	}
	return nil
}

func (m *ReviewEvent) GetReview() *Review {
	if m != nil {
		return m.Review
	}
	return nil
}

func (m *ReviewEvent) GetGUID() string {
	if m != nil && m.GUID != nil {
		return *m.GUID
	}
	return ""
}

type ReviewComment struct {
	ID                   *uint64  `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	ReviewID             *uint64  `protobuf:"varint,2,req,name=reviewID" json:"reviewID,omitempty"`
	User                 *User    `protobuf:"bytes,3,req,name=user" json:"user,omitempty"`
	Body                 *string  `protobuf:"bytes,4,req,name=body" json:"body,omitempty"`
	Path                 *string  `protobuf:"bytes,5,req,name=path" json:"path,omitempty"`
	HTMLURL              *string  `protobuf:"bytes,6,req,name=HTMLURL" json:"HTMLURL,omitempty"`
	CreatedAt            *string  `protobuf:"bytes,7,req,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt            *string  `protobuf:"bytes,8,req,name=updatedAt" json:"updatedAt,omitempty"`
	Position             *uint64  `protobuf:"varint,9,req,name=position" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReviewComment) Reset()         { *m = ReviewComment{} }
func (m *ReviewComment) String() string { return proto.CompactTextString(m) }
func (*ReviewComment) ProtoMessage()    {}
func (*ReviewComment) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{22}
}
func (m *ReviewComment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReviewComment.Unmarshal(m, b)
}
func (m *ReviewComment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReviewComment.Marshal(b, m, deterministic)
}
func (dst *ReviewComment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReviewComment.Merge(dst, src)
}
func (m *ReviewComment) XXX_Size() int {
	return xxx_messageInfo_ReviewComment.Size(m)
}
func (m *ReviewComment) XXX_DiscardUnknown() {
	xxx_messageInfo_ReviewComment.DiscardUnknown(m)
}

var xxx_messageInfo_ReviewComment proto.InternalMessageInfo

func (m *ReviewComment) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *ReviewComment) GetReviewID() uint64 {
	if m != nil && m.ReviewID != nil {
		return *m.ReviewID
	}
	return 0
}

func (m *ReviewComment) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ReviewComment) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func (m *ReviewComment) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *ReviewComment) GetHTMLURL() string {
	if m != nil && m.HTMLURL != nil {
		return *m.HTMLURL
	}
	return ""
}

func (m *ReviewComment) GetCreatedAt() string {
	if m != nil && m.CreatedAt != nil {
		return *m.CreatedAt
	}
	return ""
}

func (m *ReviewComment) GetUpdatedAt() string {
	if m != nil && m.UpdatedAt != nil {
		return *m.UpdatedAt
	}
	return ""
}

func (m *ReviewComment) GetPosition() uint64 {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return 0
}

type ListedIssueEvent struct {
	Event                *IssueEventAction `protobuf:"varint,1,req,name=event,enum=scallywag.IssueEventAction" json:"event,omitempty"`
	Actor                *User             `protobuf:"bytes,2,req,name=actor" json:"actor,omitempty"`
	Label                *Label            `protobuf:"bytes,3,req,name=label" json:"label,omitempty"`
	CreatedAt            *string           `protobuf:"bytes,4,req,name=createdAt" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListedIssueEvent) Reset()         { *m = ListedIssueEvent{} }
func (m *ListedIssueEvent) String() string { return proto.CompactTextString(m) }
func (*ListedIssueEvent) ProtoMessage()    {}
func (*ListedIssueEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{23}
}
func (m *ListedIssueEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListedIssueEvent.Unmarshal(m, b)
}
func (m *ListedIssueEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListedIssueEvent.Marshal(b, m, deterministic)
}
func (dst *ListedIssueEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListedIssueEvent.Merge(dst, src)
}
func (m *ListedIssueEvent) XXX_Size() int {
	return xxx_messageInfo_ListedIssueEvent.Size(m)
}
func (m *ListedIssueEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ListedIssueEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ListedIssueEvent proto.InternalMessageInfo

func (m *ListedIssueEvent) GetEvent() IssueEventAction {
	if m != nil && m.Event != nil {
		return *m.Event
	}
	return IssueEventAction_IEA_ASSIGNED
}

func (m *ListedIssueEvent) GetActor() *User {
	if m != nil {
		return m.Actor
	}
	return nil
}

func (m *ListedIssueEvent) GetLabel() *Label {
	if m != nil {
		return m.Label
	}
	return nil
}

func (m *ListedIssueEvent) GetCreatedAt() string {
	if m != nil && m.CreatedAt != nil {
		return *m.CreatedAt
	}
	return ""
}

type IssueCommentEvent struct {
	Action               *IssueCommentEventAction `protobuf:"varint,1,req,name=action,enum=scallywag.IssueCommentEventAction" json:"action,omitempty"`
	Issue                *Issue                   `protobuf:"bytes,2,req,name=issue" json:"issue,omitempty"`
	Comment              *IssueComment            `protobuf:"bytes,3,req,name=comment" json:"comment,omitempty"`
	Repo                 *Repo                    `protobuf:"bytes,4,req,name=repo" json:"repo,omitempty"`
	GUID                 *string                  `protobuf:"bytes,5,req,name=GUID" json:"GUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *IssueCommentEvent) Reset()         { *m = IssueCommentEvent{} }
func (m *IssueCommentEvent) String() string { return proto.CompactTextString(m) }
func (*IssueCommentEvent) ProtoMessage()    {}
func (*IssueCommentEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{24}
}
func (m *IssueCommentEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueCommentEvent.Unmarshal(m, b)
}
func (m *IssueCommentEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueCommentEvent.Marshal(b, m, deterministic)
}
func (dst *IssueCommentEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueCommentEvent.Merge(dst, src)
}
func (m *IssueCommentEvent) XXX_Size() int {
	return xxx_messageInfo_IssueCommentEvent.Size(m)
}
func (m *IssueCommentEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueCommentEvent.DiscardUnknown(m)
}

var xxx_messageInfo_IssueCommentEvent proto.InternalMessageInfo

func (m *IssueCommentEvent) GetAction() IssueCommentEventAction {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return IssueCommentEventAction_ICEA_CREATED
}

func (m *IssueCommentEvent) GetIssue() *Issue {
	if m != nil {
		return m.Issue
	}
	return nil
}

func (m *IssueCommentEvent) GetComment() *IssueComment {
	if m != nil {
		return m.Comment
	}
	return nil
}

func (m *IssueCommentEvent) GetRepo() *Repo {
	if m != nil {
		return m.Repo
	}
	return nil
}

func (m *IssueCommentEvent) GetGUID() string {
	if m != nil && m.GUID != nil {
		return *m.GUID
	}
	return ""
}

type ReviewCommentEvent struct {
	Action               *ReviewCommentEventAction `protobuf:"varint,1,req,name=action,enum=scallywag.ReviewCommentEventAction" json:"action,omitempty"`
	PullRequest          *PullRequest              `protobuf:"bytes,2,req,name=pullRequest" json:"pullRequest,omitempty"`
	Repo                 *Repo                     `protobuf:"bytes,3,req,name=repo" json:"repo,omitempty"`
	Comment              *ReviewComment            `protobuf:"bytes,4,req,name=comment" json:"comment,omitempty"`
	GUID                 *string                   `protobuf:"bytes,5,req,name=GUID" json:"GUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ReviewCommentEvent) Reset()         { *m = ReviewCommentEvent{} }
func (m *ReviewCommentEvent) String() string { return proto.CompactTextString(m) }
func (*ReviewCommentEvent) ProtoMessage()    {}
func (*ReviewCommentEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{25}
}
func (m *ReviewCommentEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReviewCommentEvent.Unmarshal(m, b)
}
func (m *ReviewCommentEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReviewCommentEvent.Marshal(b, m, deterministic)
}
func (dst *ReviewCommentEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReviewCommentEvent.Merge(dst, src)
}
func (m *ReviewCommentEvent) XXX_Size() int {
	return xxx_messageInfo_ReviewCommentEvent.Size(m)
}
func (m *ReviewCommentEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ReviewCommentEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ReviewCommentEvent proto.InternalMessageInfo

func (m *ReviewCommentEvent) GetAction() ReviewCommentEventAction {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ReviewCommentEventAction_RCEA_CREATED
}

func (m *ReviewCommentEvent) GetPullRequest() *PullRequest {
	if m != nil {
		return m.PullRequest
	}
	return nil
}

func (m *ReviewCommentEvent) GetRepo() *Repo {
	if m != nil {
		return m.Repo
	}
	return nil
}

func (m *ReviewCommentEvent) GetComment() *ReviewComment {
	if m != nil {
		return m.Comment
	}
	return nil
}

func (m *ReviewCommentEvent) GetGUID() string {
	if m != nil && m.GUID != nil {
		return *m.GUID
	}
	return ""
}

type DraftReview struct {
	CommitSHA            *string               `protobuf:"bytes,1,opt,name=commitSHA" json:"commitSHA,omitempty"`
	Body                 *string               `protobuf:"bytes,2,req,name=body" json:"body,omitempty"`
	Action               *ReviewAction         `protobuf:"varint,3,opt,name=action,enum=scallywag.ReviewAction" json:"action,omitempty"`
	Comments             []*DraftReviewComment `protobuf:"bytes,4,rep,name=comments" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DraftReview) Reset()         { *m = DraftReview{} }
func (m *DraftReview) String() string { return proto.CompactTextString(m) }
func (*DraftReview) ProtoMessage()    {}
func (*DraftReview) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{26}
}
func (m *DraftReview) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DraftReview.Unmarshal(m, b)
}
func (m *DraftReview) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DraftReview.Marshal(b, m, deterministic)
}
func (dst *DraftReview) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DraftReview.Merge(dst, src)
}
func (m *DraftReview) XXX_Size() int {
	return xxx_messageInfo_DraftReview.Size(m)
}
func (m *DraftReview) XXX_DiscardUnknown() {
	xxx_messageInfo_DraftReview.DiscardUnknown(m)
}

var xxx_messageInfo_DraftReview proto.InternalMessageInfo

func (m *DraftReview) GetCommitSHA() string {
	if m != nil && m.CommitSHA != nil {
		return *m.CommitSHA
	}
	return ""
}

func (m *DraftReview) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func (m *DraftReview) GetAction() ReviewAction {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ReviewAction_RA_APPROVE
}

func (m *DraftReview) GetComments() []*DraftReviewComment {
	if m != nil {
		return m.Comments
	}
	return nil
}

type DraftReviewComment struct {
	Path                 *string  `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Position             *uint64  `protobuf:"varint,2,req,name=position" json:"position,omitempty"`
	Body                 *string  `protobuf:"bytes,3,req,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DraftReviewComment) Reset()         { *m = DraftReviewComment{} }
func (m *DraftReviewComment) String() string { return proto.CompactTextString(m) }
func (*DraftReviewComment) ProtoMessage()    {}
func (*DraftReviewComment) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_81b385dfef9bc150, []int{27}
}
func (m *DraftReviewComment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DraftReviewComment.Unmarshal(m, b)
}
func (m *DraftReviewComment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DraftReviewComment.Marshal(b, m, deterministic)
}
func (dst *DraftReviewComment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DraftReviewComment.Merge(dst, src)
}
func (m *DraftReviewComment) XXX_Size() int {
	return xxx_messageInfo_DraftReviewComment.Size(m)
}
func (m *DraftReviewComment) XXX_DiscardUnknown() {
	xxx_messageInfo_DraftReviewComment.DiscardUnknown(m)
}

var xxx_messageInfo_DraftReviewComment proto.InternalMessageInfo

func (m *DraftReviewComment) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *DraftReviewComment) GetPosition() uint64 {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return 0
}

func (m *DraftReviewComment) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*Reaction)(nil), "scallywag.Reaction")
	proto.RegisterType((*Status)(nil), "scallywag.Status")
	proto.RegisterType((*CombinedStatus)(nil), "scallywag.CombinedStatus")
	proto.RegisterType((*User)(nil), "scallywag.User")
	proto.RegisterType((*Repo)(nil), "scallywag.Repo")
	proto.RegisterType((*Branch)(nil), "scallywag.Branch")
	proto.RegisterType((*HookConfig)(nil), "scallywag.HookConfig")
	proto.RegisterType((*Hook)(nil), "scallywag.Hook")
	proto.RegisterType((*HookRequest)(nil), "scallywag.HookRequest")
	proto.RegisterType((*Milestone)(nil), "scallywag.Milestone")
	proto.RegisterType((*Label)(nil), "scallywag.Label")
	proto.RegisterType((*Issue)(nil), "scallywag.Issue")
	proto.RegisterType((*IssueComment)(nil), "scallywag.IssueComment")
	proto.RegisterType((*IssueSearchResult)(nil), "scallywag.IssueSearchResult")
	proto.RegisterType((*IssueEvent)(nil), "scallywag.IssueEvent")
	proto.RegisterType((*PullRequestBranch)(nil), "scallywag.PullRequestBranch")
	proto.RegisterType((*PullRequest)(nil), "scallywag.PullRequest")
	proto.RegisterType((*Commit)(nil), "scallywag.Commit")
	proto.RegisterType((*PushEvent)(nil), "scallywag.PushEvent")
	proto.RegisterType((*StatusEvent)(nil), "scallywag.StatusEvent")
	proto.RegisterType((*Review)(nil), "scallywag.Review")
	proto.RegisterType((*ReviewEvent)(nil), "scallywag.ReviewEvent")
	proto.RegisterType((*ReviewComment)(nil), "scallywag.ReviewComment")
	proto.RegisterType((*ListedIssueEvent)(nil), "scallywag.ListedIssueEvent")
	proto.RegisterType((*IssueCommentEvent)(nil), "scallywag.IssueCommentEvent")
	proto.RegisterType((*ReviewCommentEvent)(nil), "scallywag.ReviewCommentEvent")
	proto.RegisterType((*DraftReview)(nil), "scallywag.DraftReview")
	proto.RegisterType((*DraftReviewComment)(nil), "scallywag.DraftReviewComment")
	proto.RegisterEnum("scallywag.IssueEventAction", IssueEventAction_name, IssueEventAction_value)
	proto.RegisterEnum("scallywag.IssueCommentEventAction", IssueCommentEventAction_name, IssueCommentEventAction_value)
	proto.RegisterEnum("scallywag.ReviewState", ReviewState_name, ReviewState_value)
	proto.RegisterEnum("scallywag.ReviewCommentEventAction", ReviewCommentEventAction_name, ReviewCommentEventAction_value)
	proto.RegisterEnum("scallywag.ReviewAction", ReviewAction_name, ReviewAction_value)
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_types_81b385dfef9bc150) }

var fileDescriptor_types_81b385dfef9bc150 = []byte{
	// 1904 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0x4f, 0x6f, 0xeb, 0x58,
	0x15, 0x97, 0x13, 0xc7, 0x4d, 0x8e, 0xfb, 0xfa, 0x5c, 0xab, 0x74, 0xac, 0xe1, 0x21, 0x55, 0x9e,
	0x01, 0xca, 0x83, 0xf7, 0x60, 0xc2, 0x86, 0x19, 0x16, 0x28, 0xd3, 0x98, 0xf7, 0x22, 0xa5, 0x7f,
	0xe6, 0xa6, 0x45, 0xb3, 0x40, 0xaa, 0xdc, 0xf8, 0xa6, 0xb5, 0xc6, 0x89, 0x83, 0xed, 0xf4, 0xf1,
	0x24, 0xc4, 0x9e, 0x0f, 0xc0, 0x8e, 0x6f, 0x80, 0xd8, 0xb0, 0x65, 0x07, 0x1b, 0x84, 0xc4, 0xa7,
	0x60, 0x81, 0xf8, 0x06, 0x88, 0x15, 0x3a, 0xe7, 0xde, 0x6b, 0x5f, 0x27, 0x4e, 0x5b, 0x21, 0xb1,
	0xcb, 0xf9, 0x73, 0xef, 0xfd, 0x9d, 0xff, 0xc7, 0x01, 0xbb, 0x78, 0xbf, 0xe4, 0xf9, 0xeb, 0x65,
	0x96, 0x16, 0xa9, 0xdb, 0xcb, 0xa7, 0x61, 0x92, 0xbc, 0x7f, 0x17, 0xde, 0xfa, 0x1f, 0x43, 0x97,
	0xf1, 0x70, 0x5a, 0xc4, 0xe9, 0xc2, 0xf5, 0x60, 0x67, 0x9a, 0x2e, 0x0a, 0xbe, 0x28, 0x3c, 0xe3,
	0xa8, 0x75, 0xdc, 0x63, 0x8a, 0xf4, 0x7f, 0x05, 0xd6, 0xa4, 0x08, 0x8b, 0x55, 0xee, 0x1e, 0x40,
	0x27, 0x2f, 0xc2, 0x82, 0x4b, 0x0d, 0x41, 0xb8, 0x47, 0x60, 0x17, 0x61, 0x76, 0xcb, 0x8b, 0x09,
	0xc9, 0x5a, 0x47, 0xc6, 0x71, 0x8f, 0xe9, 0x2c, 0xd4, 0x88, 0x78, 0x3e, 0xcd, 0xe2, 0x25, 0x3e,
	0xe5, 0xb5, 0x85, 0x86, 0xc6, 0x2a, 0x5f, 0xff, 0x65, 0xe1, 0x99, 0x24, 0x55, 0xa4, 0xff, 0x05,
	0xec, 0x9d, 0xa4, 0xf3, 0x9b, 0x78, 0xc1, 0x23, 0x89, 0xc2, 0x81, 0x76, 0x7e, 0x17, 0x4a, 0x0c,
	0xf8, 0xd3, 0x7d, 0x05, 0xdd, 0x9c, 0x64, 0x3c, 0xf7, 0x5a, 0x47, 0xed, 0x63, 0xbb, 0xbf, 0xff,
	0xba, 0xb4, 0xf2, 0xb5, 0x38, 0xc6, 0x4a, 0x15, 0x7f, 0x09, 0xe6, 0x55, 0xce, 0x33, 0x34, 0x27,
	0x49, 0x6f, 0xe3, 0x85, 0x32, 0x87, 0x08, 0xd7, 0x05, 0x73, 0x11, 0xce, 0xd1, 0x0e, 0x64, 0xd2,
	0x6f, 0xd4, 0xe4, 0xf3, 0x30, 0x4e, 0xbc, 0xb6, 0xd0, 0x24, 0xc2, 0xdd, 0x83, 0xd6, 0x68, 0xe8,
	0x99, 0x47, 0xad, 0x63, 0x93, 0xb5, 0x46, 0x43, 0x34, 0xe2, 0xed, 0xe5, 0xe9, 0xf8, 0x8a, 0x8d,
	0xbd, 0x8e, 0x70, 0xa1, 0x24, 0xfd, 0xbf, 0x1b, 0x60, 0x32, 0xbe, 0x4c, 0xdd, 0x6f, 0x42, 0x27,
	0x7d, 0xb7, 0xe0, 0x19, 0x3d, 0x69, 0xf7, 0x9f, 0x6b, 0x30, 0x11, 0x12, 0x13, 0xd2, 0x46, 0x0c,
	0x1f, 0x42, 0x77, 0xb6, 0x4a, 0x92, 0x33, 0xe4, 0x0b, 0x18, 0x25, 0xad, 0xbf, 0x6c, 0xd6, 0x5e,
	0xc6, 0x9b, 0x66, 0x69, 0xf6, 0x15, 0x01, 0xea, 0x32, 0xfa, 0xed, 0x7e, 0x0c, 0xcf, 0x22, 0x3e,
	0x0b, 0x57, 0x49, 0xf1, 0x79, 0x16, 0x2e, 0xa6, 0x77, 0x9e, 0x45, 0x67, 0xea, 0x4c, 0x7c, 0x2f,
	0xcc, 0xa6, 0x77, 0xf1, 0x3d, 0x8f, 0xbc, 0x1d, 0x3a, 0x5d, 0xd2, 0xfe, 0x67, 0x60, 0x49, 0x2d,
	0x85, 0xd4, 0xd0, 0x90, 0xbe, 0x80, 0x1e, 0xa6, 0x1a, 0x9f, 0x16, 0x3c, 0x22, 0x13, 0xba, 0xac,
	0x62, 0xf8, 0x5f, 0x02, 0xbc, 0x4d, 0xd3, 0xaf, 0x4e, 0xd2, 0xc5, 0x2c, 0xbe, 0xc5, 0x60, 0x22,
	0x6a, 0x19, 0x4c, 0x44, 0x7c, 0x04, 0xb6, 0xcc, 0xbc, 0xcb, 0xf7, 0xcb, 0x32, 0x9d, 0x34, 0x96,
	0x7b, 0x08, 0x56, 0xce, 0xa7, 0x19, 0x2f, 0x64, 0x26, 0x49, 0xca, 0xff, 0x8d, 0x01, 0x26, 0x5e,
	0x2d, 0x03, 0x63, 0x94, 0x81, 0x69, 0x72, 0xe7, 0x21, 0x58, 0xfc, 0x9e, 0x2f, 0x8a, 0xdc, 0x6b,
	0x1f, 0xb5, 0xf1, 0x12, 0x41, 0x21, 0x1f, 0x2b, 0xe2, 0x9e, 0x93, 0x27, 0xbb, 0x4c, 0x52, 0xee,
	0x2b, 0xb0, 0xa6, 0x04, 0x99, 0x5c, 0x69, 0xf7, 0xbf, 0xa6, 0x85, 0xae, 0xb2, 0x87, 0x49, 0x25,
	0xff, 0xcf, 0x06, 0xd8, 0xc8, 0x66, 0xfc, 0x17, 0x2b, 0x9e, 0x17, 0x9a, 0x9f, 0x0c, 0x1d, 0x82,
	0x7c, 0x0a, 0x8d, 0xac, 0x9e, 0x7a, 0x01, 0xbd, 0x30, 0x8a, 0x02, 0x1d, 0x5d, 0xc5, 0xd0, 0x80,
	0x60, 0xa5, 0x3c, 0x06, 0x44, 0xb3, 0xb3, 0x53, 0xb3, 0xd3, 0x87, 0xdd, 0x8c, 0xcf, 0xd3, 0x7b,
	0x2e, 0xdf, 0xb1, 0x48, 0x5a, 0xe3, 0xf9, 0x9f, 0x42, 0xef, 0x34, 0x4e, 0x78, 0x5e, 0xa4, 0x0b,
	0xaa, 0x81, 0x22, 0x2e, 0x92, 0xb2, 0xf8, 0x89, 0xc0, 0xeb, 0x17, 0xab, 0xf9, 0x0d, 0xcf, 0xc8,
	0xb9, 0x26, 0x93, 0x94, 0xcf, 0xa1, 0x33, 0x0e, 0x6f, 0x78, 0xd2, 0x10, 0xe0, 0xa6, 0x68, 0x6c,
	0x74, 0x88, 0xd6, 0x7a, 0x87, 0x38, 0x80, 0xce, 0x34, 0x4d, 0xd2, 0x4c, 0x26, 0xb8, 0x20, 0xfc,
	0x7f, 0xb6, 0xa0, 0x33, 0xca, 0xf3, 0x15, 0x77, 0x3f, 0x02, 0x73, 0x95, 0x6f, 0x2f, 0x2c, 0x12,
	0x6e, 0x43, 0x5b, 0xd9, 0xd6, 0xd6, 0x6d, 0x2b, 0xdb, 0x9d, 0xa9, 0xb7, 0xbb, 0xad, 0x55, 0xee,
	0x1e, 0x83, 0x95, 0xa0, 0xcd, 0xc2, 0x99, 0x76, 0xdf, 0xd1, 0x40, 0x90, 0x33, 0x98, 0x94, 0xbb,
	0xaf, 0xa0, 0x17, 0xe6, 0x79, 0x7c, 0xbb, 0xe0, 0x3c, 0xf7, 0x76, 0x48, 0x79, 0x03, 0x71, 0xa5,
	0x81, 0x1e, 0xbb, 0x49, 0xa3, 0xf7, 0x5e, 0x57, 0x78, 0x0c, 0x7f, 0x63, 0x92, 0x4c, 0x33, 0x1e,
	0x16, 0x3c, 0x1a, 0x14, 0x5e, 0x8f, 0x04, 0x15, 0x03, 0xa5, 0xab, 0x65, 0x24, 0xa5, 0x20, 0xa4,
	0x25, 0xc3, 0xed, 0x43, 0x6f, 0xae, 0xe2, 0xea, 0xd9, 0xe4, 0xb0, 0x03, 0xed, 0xf9, 0x32, 0xe6,
	0xac, 0x52, 0xf3, 0xff, 0x60, 0xc0, 0x2e, 0x79, 0xfa, 0x24, 0x9d, 0xcf, 0xf9, 0xa2, 0x28, 0x8b,
	0x0c, 0xf3, 0x59, 0x16, 0x19, 0x81, 0x6c, 0x69, 0x20, 0x55, 0x50, 0xda, 0x94, 0xa9, 0x5b, 0x82,
	0x52, 0x6b, 0x5e, 0x86, 0xee, 0xd0, 0x9a, 0x8d, 0x1d, 0x92, 0x6d, 0xb3, 0xd1, 0x12, 0xd2, 0x92,
	0xe1, 0x4f, 0x60, 0x9f, 0xe0, 0x4e, 0x38, 0x76, 0x2d, 0xc6, 0xf3, 0x55, 0x52, 0x50, 0x9c, 0xd3,
	0x22, 0x4c, 0x08, 0xb6, 0xc9, 0x04, 0x81, 0x71, 0x8b, 0x51, 0x55, 0x0d, 0x0f, 0x3d, 0x6e, 0x74,
	0x07, 0x93, 0x72, 0xff, 0x6f, 0x06, 0x00, 0x71, 0xa8, 0x40, 0xdc, 0x1f, 0x8a, 0x02, 0x4e, 0xc5,
	0x04, 0xd9, 0xeb, 0x7f, 0x7d, 0xfd, 0x20, 0xa9, 0x0d, 0x48, 0x85, 0x49, 0x55, 0xf7, 0x5b, 0xd0,
	0xa1, 0xdb, 0xc8, 0x51, 0x4d, 0x8f, 0x09, 0x31, 0xfa, 0x2e, 0xe3, 0xcb, 0x94, 0x52, 0xb2, 0xee,
	0x3b, 0x9c, 0x24, 0x8c, 0x84, 0x78, 0x19, 0xa5, 0x14, 0xa5, 0x68, 0x53, 0xc6, 0x09, 0x31, 0x06,
	0xe7, 0xcd, 0xd5, 0x68, 0x28, 0x33, 0x96, 0x7e, 0xfb, 0x3f, 0x87, 0xfd, 0x8b, 0x55, 0x92, 0xc8,
	0x0e, 0x25, 0xfb, 0xb9, 0x03, 0xed, 0x8c, 0xcf, 0x54, 0xb9, 0x66, 0x7c, 0x86, 0x9c, 0xc9, 0xdb,
	0x81, 0x0c, 0x2b, 0xfe, 0x7c, 0x12, 0x32, 0xff, 0x77, 0x26, 0xd8, 0xda, 0xf5, 0x5a, 0xe9, 0x19,
	0xb5, 0xd2, 0xd3, 0xa2, 0xdf, 0xaa, 0x97, 0x53, 0x95, 0x3c, 0x0f, 0x54, 0xf4, 0x0f, 0xc0, 0xbc,
	0x09, 0x73, 0x2e, 0xed, 0x7f, 0xa1, 0x29, 0x6d, 0xd8, 0xc6, 0x48, 0x13, 0x4f, 0xdc, 0xf1, 0x30,
	0x92, 0x6d, 0xfc, 0x91, 0x13, 0xa8, 0x59, 0x75, 0x07, 0x4b, 0xef, 0x0e, 0x2a, 0xdf, 0x77, 0xb4,
	0x7c, 0xff, 0x09, 0xb8, 0x99, 0xb8, 0x80, 0x47, 0x8c, 0xdf, 0xc7, 0xfc, 0x1d, 0xcf, 0x72, 0xaf,
	0xdb, 0x5c, 0xe0, 0x0d, 0xaa, 0xf5, 0xc6, 0xd0, 0x7b, 0xb4, 0x31, 0x94, 0x1d, 0x0a, 0xf4, 0x0e,
	0x75, 0x00, 0x9d, 0x28, 0x0b, 0x67, 0x05, 0x95, 0x76, 0x97, 0x09, 0x02, 0x03, 0x30, 0xe7, 0xd9,
	0x2d, 0x8f, 0xbc, 0x5d, 0x31, 0xd8, 0x04, 0x55, 0x2f, 0xb2, 0x67, 0x0f, 0x16, 0xd9, 0xde, 0x5a,
	0x91, 0xe1, 0x8e, 0x40, 0xb7, 0x60, 0x82, 0x3c, 0x17, 0x3b, 0x89, 0xa2, 0xf1, 0x24, 0xfd, 0x0e,
	0x6f, 0x12, 0xee, 0x39, 0xe2, 0x64, 0xc9, 0xf0, 0x7f, 0x0d, 0x16, 0x36, 0x92, 0xb8, 0xd0, 0x86,
	0x75, 0x4f, 0x6d, 0x51, 0x73, 0x9e, 0xe7, 0xe1, 0xad, 0x9a, 0x10, 0x8a, 0x44, 0xbb, 0xc2, 0x28,
	0xe2, 0x91, 0x9c, 0x89, 0x82, 0x40, 0x7d, 0x31, 0xb4, 0x22, 0xcf, 0x24, 0xbe, 0x22, 0x09, 0x5d,
	0x1a, 0xc5, 0xb3, 0x98, 0x47, 0x72, 0xf8, 0x95, 0xb4, 0xff, 0xaf, 0x16, 0xf4, 0x2e, 0x56, 0xf9,
	0x9d, 0x28, 0xe4, 0xcd, 0xac, 0x3f, 0x04, 0xeb, 0x86, 0xcf, 0xd2, 0x4c, 0x81, 0x90, 0x14, 0x61,
	0x98, 0x15, 0x32, 0x2b, 0x11, 0x03, 0x12, 0xb4, 0xbe, 0x0a, 0x97, 0xc9, 0xad, 0x41, 0x91, 0x28,
	0x89, 0x78, 0xc2, 0x0b, 0x1e, 0xc9, 0x15, 0x4c, 0x91, 0xf8, 0xc2, 0x2c, 0xcd, 0xa6, 0x3c, 0xa2,
	0xb4, 0xea, 0x32, 0x49, 0x89, 0x55, 0x78, 0xbe, 0x0c, 0x33, 0x2e, 0x53, 0x4b, 0x91, 0xee, 0x77,
	0x49, 0x32, 0x8f, 0x0b, 0x95, 0x52, 0xfa, 0x96, 0x2b, 0xbc, 0xc9, 0x94, 0x86, 0xfb, 0x6d, 0xb0,
	0x96, 0xab, 0xfc, 0x8e, 0x67, 0x34, 0x1c, 0x1a, 0xd2, 0x48, 0x8a, 0x51, 0x31, 0xe7, 0x8b, 0x88,
	0x67, 0x94, 0x44, 0x4d, 0x8a, 0x42, 0x5c, 0x96, 0xbd, 0xfd, 0x50, 0x43, 0x52, 0x8d, 0x66, 0x57,
	0x6b, 0x34, 0xbf, 0x6d, 0x81, 0x2d, 0x96, 0xf0, 0xd2, 0xdb, 0x98, 0x30, 0x62, 0x74, 0x50, 0x47,
	0x29, 0xf3, 0x58, 0x6c, 0x7b, 0xd5, 0x87, 0xc5, 0x23, 0x9f, 0x0d, 0x2f, 0xa0, 0x27, 0xbe, 0x33,
	0xaa, 0xe1, 0x51, 0x31, 0x64, 0x66, 0x75, 0xa8, 0xd5, 0xeb, 0x6b, 0xa0, 0xa5, 0xed, 0x60, 0xda,
	0x87, 0xc7, 0x4e, 0xed, 0xc3, 0x43, 0xf3, 0x4b, 0xb7, 0x79, 0x7a, 0xad, 0xfb, 0xa5, 0xb7, 0xa1,
	0xd6, 0xe0, 0x17, 0xd0, 0xfc, 0xf2, 0x27, 0x03, 0x2c, 0x51, 0xfa, 0x1b, 0x1b, 0xab, 0xea, 0x7d,
	0xad, 0x87, 0x7a, 0x9f, 0xea, 0x40, 0x6d, 0xad, 0x03, 0x7d, 0x4f, 0xdf, 0x59, 0xf6, 0xfa, 0x87,
	0x35, 0x34, 0xf8, 0x14, 0x7d, 0x91, 0x3d, 0xbe, 0xcb, 0x1c, 0x81, 0x9d, 0xaf, 0x6e, 0xe6, 0x71,
	0xa1, 0xc6, 0x2b, 0x2d, 0x64, 0x1a, 0xcb, 0xff, 0x8b, 0x01, 0xb6, 0xb8, 0x52, 0x44, 0xf5, 0xb0,
	0x36, 0x0c, 0x7b, 0xe5, 0xbc, 0xfb, 0x11, 0xd8, 0xcb, 0xaa, 0xb1, 0x4a, 0x8b, 0x0e, 0x9b, 0xdb,
	0x2e, 0xd3, 0x55, 0x9f, 0x36, 0x01, 0xbf, 0x03, 0x56, 0x46, 0x28, 0xe4, 0x08, 0xd8, 0xdf, 0xb0,
	0x98, 0x49, 0x85, 0xc6, 0x21, 0xf8, 0x1f, 0x03, 0x9e, 0x09, 0xb5, 0xf5, 0xbd, 0x46, 0x85, 0xe2,
	0x43, 0xe8, 0x8a, 0xf3, 0xa3, 0xa1, 0xdc, 0x1a, 0x4b, 0xfa, 0x69, 0x23, 0x4a, 0x85, 0xc9, 0xd4,
	0xc2, 0xe4, 0x82, 0xb9, 0x0c, 0x8b, 0x3b, 0x05, 0x05, 0x7f, 0xeb, 0xc1, 0xb0, 0xea, 0xc1, 0xa8,
	0xb5, 0xe8, 0x9d, 0x07, 0x77, 0xbd, 0xee, 0xfa, 0xae, 0xf7, 0x21, 0x74, 0x97, 0x69, 0x1e, 0x53,
	0x60, 0x7a, 0x02, 0xbe, 0xa2, 0xfd, 0x3f, 0x1a, 0xe0, 0x8c, 0x63, 0x9c, 0x40, 0xda, 0x52, 0xf3,
	0x09, 0x74, 0xe8, 0x13, 0xe1, 0x29, 0x3b, 0x8d, 0xd0, 0xc4, 0xaf, 0xda, 0x70, 0x5a, 0xa4, 0x5b,
	0xd3, 0x55, 0x48, 0xab, 0x65, 0xa5, 0xfd, 0xf0, 0xb2, 0x52, 0x33, 0xd7, 0x5c, 0x33, 0xd7, 0xff,
	0x87, 0x21, 0x37, 0x3b, 0x19, 0x30, 0x81, 0xfa, 0xb3, 0xb5, 0x55, 0xcc, 0x5f, 0x87, 0xad, 0x6b,
	0xff, 0x8f, 0x1b, 0xd9, 0x27, 0xa2, 0xff, 0xa2, 0x6f, 0x84, 0x05, 0x1f, 0x6c, 0x79, 0x84, 0x29,
	0xbd, 0x32, 0x85, 0xcd, 0xa7, 0xf4, 0x4c, 0x3d, 0x2f, 0xff, 0x6d, 0x80, 0x5b, 0xcb, 0x4b, 0x61,
	0xe6, 0x8f, 0xd7, 0xcc, 0xfc, 0x68, 0x23, 0xdb, 0x1f, 0xb0, 0xf3, 0xff, 0x5c, 0x89, 0xfd, 0xca,
	0x3d, 0xc2, 0x5c, 0x6f, 0x1b, 0xb8, 0xca, 0x3f, 0x4d, 0xa6, 0xff, 0xde, 0x00, 0x7b, 0x88, 0x2b,
	0x8b, 0xec, 0x8d, 0x98, 0x0e, 0x34, 0xd4, 0xaa, 0xa1, 0x51, 0x31, 0x1a, 0x3f, 0x3b, 0xbe, 0x5f,
	0x7a, 0x09, 0x67, 0xc6, 0x5e, 0x2d, 0x4e, 0xe2, 0xd2, 0x35, 0xcf, 0x7c, 0x0a, 0x5d, 0x89, 0x28,
	0xa7, 0x25, 0xc2, 0xee, 0x7f, 0x43, 0x3b, 0xa2, 0x81, 0x51, 0x06, 0x94, 0xea, 0xfe, 0x97, 0xe0,
	0x6e, 0xca, 0xcb, 0xfa, 0x36, 0xb4, 0xfa, 0xd6, 0x2b, 0xb1, 0x55, 0xaf, 0xc4, 0xa6, 0x56, 0xfe,
	0xf2, 0xaf, 0x06, 0x38, 0xeb, 0x15, 0xe7, 0x3a, 0xb0, 0x3b, 0x0a, 0x06, 0xd7, 0x83, 0xc9, 0x64,
	0xf4, 0xe6, 0x2c, 0x18, 0x3a, 0x86, 0xeb, 0xc2, 0x1e, 0x72, 0xae, 0xce, 0x4a, 0x5e, 0xcb, 0x7d,
	0x0e, 0x36, 0xf2, 0xc6, 0x83, 0xcf, 0x83, 0x71, 0x30, 0x74, 0xda, 0xee, 0x3e, 0x3c, 0x13, 0x4a,
	0x8a, 0x65, 0xba, 0x7b, 0x00, 0xc8, 0x3a, 0xbf, 0x08, 0xf0, 0x4c, 0x47, 0xd1, 0xc1, 0x70, 0x74,
	0x19, 0x0c, 0x1d, 0x4b, 0xdd, 0x7b, 0x3a, 0x1a, 0x07, 0x93, 0xcb, 0x73, 0xd4, 0xd9, 0x71, 0x0f,
	0xc0, 0x41, 0xde, 0x30, 0xd0, 0xb8, 0x5d, 0x75, 0xf2, 0x64, 0x7c, 0x3e, 0x09, 0x86, 0x4e, 0x4f,
	0x61, 0x64, 0x81, 0xbc, 0x1b, 0x5e, 0x9e, 0xc3, 0x07, 0x5b, 0x8a, 0x90, 0x94, 0x4f, 0xf0, 0x34,
	0x0b, 0x06, 0x97, 0x64, 0x90, 0xe2, 0x08, 0x24, 0xd7, 0x4e, 0xab, 0xe4, 0x0c, 0x83, 0x71, 0x80,
	0x3a, 0xed, 0x97, 0x89, 0x9a, 0x3d, 0xe2, 0x0f, 0xc6, 0xe7, 0x60, 0xb3, 0xc9, 0xf5, 0xe0, 0xe2,
	0x82, 0x9d, 0xff, 0x8c, 0xee, 0xf0, 0xe0, 0x80, 0x4d, 0xae, 0x4f, 0xde, 0x0e, 0xce, 0xde, 0x04,
	0x93, 0x6b, 0x16, 0x7c, 0x71, 0x15, 0x4c, 0x2e, 0xc9, 0x35, 0x0e, 0xec, 0xa2, 0xe4, 0xfc, 0xf4,
	0x34, 0x38, 0xa3, 0xbb, 0x24, 0x67, 0x38, 0x9a, 0x9c, 0x8e, 0x26, 0x13, 0xe5, 0x1a, 0x36, 0xb9,
	0xbe, 0x08, 0xce, 0x86, 0xa3, 0xb3, 0x37, 0x4e, 0xe7, 0xe5, 0x05, 0x78, 0xdb, 0x8a, 0x8b, 0x4e,
	0x6f, 0xe0, 0x67, 0x1b, 0xf8, 0x59, 0x1d, 0xff, 0x4f, 0x61, 0x57, 0x4f, 0x44, 0x7a, 0x71, 0xa0,
	0x0c, 0x70, 0x0c, 0xf7, 0x10, 0x5c, 0x36, 0x50, 0xb8, 0x95, 0x1d, 0x4e, 0x4b, 0xea, 0x49, 0xf4,
	0x4e, 0xfb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x91, 0x05, 0x45, 0xda, 0x15, 0x00, 0x00,
}
