// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package scallywag

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type State int32

const (
	State_OPEN   State = 0
	State_CLOSED State = 1
)

var State_name = map[int32]string{
	0: "OPEN",
	1: "CLOSED",
}

var State_value = map[string]int32{
	"OPEN":   0,
	"CLOSED": 1,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}

func (State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

type Confirmation struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Confirmation) Reset()         { *m = Confirmation{} }
func (m *Confirmation) String() string { return proto.CompactTextString(m) }
func (*Confirmation) ProtoMessage()    {}
func (*Confirmation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *Confirmation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Confirmation.Unmarshal(m, b)
}
func (m *Confirmation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Confirmation.Marshal(b, m, deterministic)
}
func (m *Confirmation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Confirmation.Merge(m, src)
}
func (m *Confirmation) XXX_Size() int {
	return xxx_messageInfo_Confirmation.Size(m)
}
func (m *Confirmation) XXX_DiscardUnknown() {
	xxx_messageInfo_Confirmation.DiscardUnknown(m)
}

var xxx_messageInfo_Confirmation proto.InternalMessageInfo

type Provider struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	URL                  string   `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Provider) Reset()         { *m = Provider{} }
func (m *Provider) String() string { return proto.CompactTextString(m) }
func (*Provider) ProtoMessage()    {}
func (*Provider) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *Provider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Provider.Unmarshal(m, b)
}
func (m *Provider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Provider.Marshal(b, m, deterministic)
}
func (m *Provider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provider.Merge(m, src)
}
func (m *Provider) XXX_Size() int {
	return xxx_messageInfo_Provider.Size(m)
}
func (m *Provider) XXX_DiscardUnknown() {
	xxx_messageInfo_Provider.DiscardUnknown(m)
}

var xxx_messageInfo_Provider proto.InternalMessageInfo

func (m *Provider) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Provider) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *Provider) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Provider) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type String struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (m *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(m, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Branch struct {
	Repo                 string   `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Branch) Reset()         { *m = Branch{} }
func (m *Branch) String() string { return proto.CompactTextString(m) }
func (*Branch) ProtoMessage()    {}
func (*Branch) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *Branch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Branch.Unmarshal(m, b)
}
func (m *Branch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Branch.Marshal(b, m, deterministic)
}
func (m *Branch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Branch.Merge(m, src)
}
func (m *Branch) XXX_Size() int {
	return xxx_messageInfo_Branch.Size(m)
}
func (m *Branch) XXX_DiscardUnknown() {
	xxx_messageInfo_Branch.DiscardUnknown(m)
}

var xxx_messageInfo_Branch proto.InternalMessageInfo

func (m *Branch) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *Branch) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Branch) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Collaborator struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Repo                 string   `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	Org                  string   `protobuf:"bytes,3,opt,name=org,proto3" json:"org,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Collaborator) Reset()         { *m = Collaborator{} }
func (m *Collaborator) String() string { return proto.CompactTextString(m) }
func (*Collaborator) ProtoMessage()    {}
func (*Collaborator) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

func (m *Collaborator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collaborator.Unmarshal(m, b)
}
func (m *Collaborator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collaborator.Marshal(b, m, deterministic)
}
func (m *Collaborator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collaborator.Merge(m, src)
}
func (m *Collaborator) XXX_Size() int {
	return xxx_messageInfo_Collaborator.Size(m)
}
func (m *Collaborator) XXX_DiscardUnknown() {
	xxx_messageInfo_Collaborator.DiscardUnknown(m)
}

var xxx_messageInfo_Collaborator proto.InternalMessageInfo

func (m *Collaborator) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Collaborator) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *Collaborator) GetOrg() string {
	if m != nil {
		return m.Org
	}
	return ""
}

type Repository struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	HTMLURL              string   `protobuf:"bytes,2,opt,name=HTMLURL,proto3" json:"HTMLURL,omitempty"`
	SSHURL               string   `protobuf:"bytes,3,opt,name=SSHURL,proto3" json:"SSHURL,omitempty"`
	CloneURL             string   `protobuf:"bytes,4,opt,name=CloneURL,proto3" json:"CloneURL,omitempty"`
	AllowMergeCommit     bool     `protobuf:"varint,5,opt,name=AllowMergeCommit,proto3" json:"AllowMergeCommit,omitempty"`
	Language             string   `protobuf:"bytes,6,opt,name=Language,proto3" json:"Language,omitempty"`
	Fork                 bool     `protobuf:"varint,7,opt,name=Fork,proto3" json:"Fork,omitempty"`
	Stars                int64    `protobuf:"varint,8,opt,name=Stars,proto3" json:"Stars,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Repository) Reset()         { *m = Repository{} }
func (m *Repository) String() string { return proto.CompactTextString(m) }
func (*Repository) ProtoMessage()    {}
func (*Repository) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{5}
}

func (m *Repository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repository.Unmarshal(m, b)
}
func (m *Repository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repository.Marshal(b, m, deterministic)
}
func (m *Repository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repository.Merge(m, src)
}
func (m *Repository) XXX_Size() int {
	return xxx_messageInfo_Repository.Size(m)
}
func (m *Repository) XXX_DiscardUnknown() {
	xxx_messageInfo_Repository.DiscardUnknown(m)
}

var xxx_messageInfo_Repository proto.InternalMessageInfo

func (m *Repository) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Repository) GetHTMLURL() string {
	if m != nil {
		return m.HTMLURL
	}
	return ""
}

func (m *Repository) GetSSHURL() string {
	if m != nil {
		return m.SSHURL
	}
	return ""
}

func (m *Repository) GetCloneURL() string {
	if m != nil {
		return m.CloneURL
	}
	return ""
}

func (m *Repository) GetAllowMergeCommit() bool {
	if m != nil {
		return m.AllowMergeCommit
	}
	return false
}

func (m *Repository) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Repository) GetFork() bool {
	if m != nil {
		return m.Fork
	}
	return false
}

func (m *Repository) GetStars() int64 {
	if m != nil {
		return m.Stars
	}
	return 0
}

type RepositoryInfo struct {
	Org                  string   `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	IsPrivate            bool     `protobuf:"varint,3,opt,name=isPrivate,proto3" json:"isPrivate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepositoryInfo) Reset()         { *m = RepositoryInfo{} }
func (m *RepositoryInfo) String() string { return proto.CompactTextString(m) }
func (*RepositoryInfo) ProtoMessage()    {}
func (*RepositoryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{6}
}

func (m *RepositoryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepositoryInfo.Unmarshal(m, b)
}
func (m *RepositoryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepositoryInfo.Marshal(b, m, deterministic)
}
func (m *RepositoryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepositoryInfo.Merge(m, src)
}
func (m *RepositoryInfo) XXX_Size() int {
	return xxx_messageInfo_RepositoryInfo.Size(m)
}
func (m *RepositoryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RepositoryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RepositoryInfo proto.InternalMessageInfo

func (m *RepositoryInfo) GetOrg() string {
	if m != nil {
		return m.Org
	}
	return ""
}

func (m *RepositoryInfo) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *RepositoryInfo) GetIsPrivate() bool {
	if m != nil {
		return m.IsPrivate
	}
	return false
}

type ForkInfo struct {
	UpstreamOwner        string      `protobuf:"bytes,1,opt,name=upstreamOwner,proto3" json:"upstreamOwner,omitempty"`
	DestinationOwner     string      `protobuf:"bytes,2,opt,name=destinationOwner,proto3" json:"destinationOwner,omitempty"`
	Repo                 *Repository `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ForkInfo) Reset()         { *m = ForkInfo{} }
func (m *ForkInfo) String() string { return proto.CompactTextString(m) }
func (*ForkInfo) ProtoMessage()    {}
func (*ForkInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{7}
}

func (m *ForkInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForkInfo.Unmarshal(m, b)
}
func (m *ForkInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForkInfo.Marshal(b, m, deterministic)
}
func (m *ForkInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForkInfo.Merge(m, src)
}
func (m *ForkInfo) XXX_Size() int {
	return xxx_messageInfo_ForkInfo.Size(m)
}
func (m *ForkInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ForkInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ForkInfo proto.InternalMessageInfo

func (m *ForkInfo) GetUpstreamOwner() string {
	if m != nil {
		return m.UpstreamOwner
	}
	return ""
}

func (m *ForkInfo) GetDestinationOwner() string {
	if m != nil {
		return m.DestinationOwner
	}
	return ""
}

func (m *ForkInfo) GetRepo() *Repository {
	if m != nil {
		return m.Repo
	}
	return nil
}

type Organization struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Organization) Reset()         { *m = Organization{} }
func (m *Organization) String() string { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()    {}
func (*Organization) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{8}
}

func (m *Organization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Organization.Unmarshal(m, b)
}
func (m *Organization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Organization.Marshal(b, m, deterministic)
}
func (m *Organization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Organization.Merge(m, src)
}
func (m *Organization) XXX_Size() int {
	return xxx_messageInfo_Organization.Size(m)
}
func (m *Organization) XXX_DiscardUnknown() {
	xxx_messageInfo_Organization.DiscardUnknown(m)
}

var xxx_messageInfo_Organization proto.InternalMessageInfo

func (m *Organization) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type User struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	URL                  string   `protobuf:"bytes,4,opt,name=URL,proto3" json:"URL,omitempty"`
	AvatarURL            string   `protobuf:"bytes,5,opt,name=AvatarURL,proto3" json:"AvatarURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{9}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *User) GetAvatarURL() string {
	if m != nil {
		return m.AvatarURL
	}
	return ""
}

type PullRequest struct {
	Base                 string   `protobuf:"bytes,1,opt,name=Base,proto3" json:"Base,omitempty"`
	Head                 string   `protobuf:"bytes,2,opt,name=Head,proto3" json:"Head,omitempty"`
	URL                  string   `protobuf:"bytes,3,opt,name=URL,proto3" json:"URL,omitempty"`
	Repository           string   `protobuf:"bytes,4,opt,name=Repository,proto3" json:"Repository,omitempty"`
	Owner                string   `protobuf:"bytes,5,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Number               int64    `protobuf:"varint,6,opt,name=Number,proto3" json:"Number,omitempty"`
	Mergeable            bool     `protobuf:"varint,7,opt,name=Mergeable,proto3" json:"Mergeable,omitempty"`
	Merged               bool     `protobuf:"varint,8,opt,name=Merged,proto3" json:"Merged,omitempty"`
	State                State    `protobuf:"varint,9,opt,name=State,proto3,enum=scallywag.State" json:"State,omitempty"`
	StatusesURL          string   `protobuf:"bytes,10,opt,name=StatusesURL,proto3" json:"StatusesURL,omitempty"`
	IssueURL             string   `protobuf:"bytes,11,opt,name=IssueURL,proto3" json:"IssueURL,omitempty"`
	DiffURL              string   `protobuf:"bytes,12,opt,name=DiffURL,proto3" json:"DiffURL,omitempty"`
	MergeCommitSHA       string   `protobuf:"bytes,13,opt,name=MergeCommitSHA,proto3" json:"MergeCommitSHA,omitempty"`
	CloseAt              string   `protobuf:"bytes,14,opt,name=CloseAt,proto3" json:"CloseAt,omitempty"`
	MergedAt             string   `protobuf:"bytes,15,opt,name=MergedAt,proto3" json:"MergedAt,omitempty"`
	LastCommitSha        string   `protobuf:"bytes,16,opt,name=LastCommitSha,proto3" json:"LastCommitSha,omitempty"`
	Title                string   `protobuf:"bytes,17,opt,name=Title,proto3" json:"Title,omitempty"`
	Body                 string   `protobuf:"bytes,18,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullRequest) Reset()         { *m = PullRequest{} }
func (m *PullRequest) String() string { return proto.CompactTextString(m) }
func (*PullRequest) ProtoMessage()    {}
func (*PullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{10}
}

func (m *PullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRequest.Unmarshal(m, b)
}
func (m *PullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRequest.Marshal(b, m, deterministic)
}
func (m *PullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRequest.Merge(m, src)
}
func (m *PullRequest) XXX_Size() int {
	return xxx_messageInfo_PullRequest.Size(m)
}
func (m *PullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullRequest proto.InternalMessageInfo

func (m *PullRequest) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *PullRequest) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *PullRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *PullRequest) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *PullRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *PullRequest) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *PullRequest) GetMergeable() bool {
	if m != nil {
		return m.Mergeable
	}
	return false
}

func (m *PullRequest) GetMerged() bool {
	if m != nil {
		return m.Merged
	}
	return false
}

func (m *PullRequest) GetState() State {
	if m != nil {
		return m.State
	}
	return State_OPEN
}

func (m *PullRequest) GetStatusesURL() string {
	if m != nil {
		return m.StatusesURL
	}
	return ""
}

func (m *PullRequest) GetIssueURL() string {
	if m != nil {
		return m.IssueURL
	}
	return ""
}

func (m *PullRequest) GetDiffURL() string {
	if m != nil {
		return m.DiffURL
	}
	return ""
}

func (m *PullRequest) GetMergeCommitSHA() string {
	if m != nil {
		return m.MergeCommitSHA
	}
	return ""
}

func (m *PullRequest) GetCloseAt() string {
	if m != nil {
		return m.CloseAt
	}
	return ""
}

func (m *PullRequest) GetMergedAt() string {
	if m != nil {
		return m.MergedAt
	}
	return ""
}

func (m *PullRequest) GetLastCommitSha() string {
	if m != nil {
		return m.LastCommitSha
	}
	return ""
}

func (m *PullRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PullRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type PullRequestComment struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullRequestComment) Reset()         { *m = PullRequestComment{} }
func (m *PullRequestComment) String() string { return proto.CompactTextString(m) }
func (*PullRequestComment) ProtoMessage()    {}
func (*PullRequestComment) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{11}
}

func (m *PullRequestComment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRequestComment.Unmarshal(m, b)
}
func (m *PullRequestComment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRequestComment.Marshal(b, m, deterministic)
}
func (m *PullRequestComment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRequestComment.Merge(m, src)
}
func (m *PullRequestComment) XXX_Size() int {
	return xxx_messageInfo_PullRequestComment.Size(m)
}
func (m *PullRequestComment) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRequestComment.DiscardUnknown(m)
}

var xxx_messageInfo_PullRequestComment proto.InternalMessageInfo

type Webhook struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo                 string   `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo,omitempty"`
	URL                  string   `protobuf:"bytes,4,opt,name=URL,proto3" json:"URL,omitempty"`
	Secret               string   `protobuf:"bytes,5,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Webhook) Reset()         { *m = Webhook{} }
func (m *Webhook) String() string { return proto.CompactTextString(m) }
func (*Webhook) ProtoMessage()    {}
func (*Webhook) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{12}
}

func (m *Webhook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Webhook.Unmarshal(m, b)
}
func (m *Webhook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Webhook.Marshal(b, m, deterministic)
}
func (m *Webhook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Webhook.Merge(m, src)
}
func (m *Webhook) XXX_Size() int {
	return xxx_messageInfo_Webhook.Size(m)
}
func (m *Webhook) XXX_DiscardUnknown() {
	xxx_messageInfo_Webhook.DiscardUnknown(m)
}

var xxx_messageInfo_Webhook proto.InternalMessageInfo

func (m *Webhook) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Webhook) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Webhook) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *Webhook) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *Webhook) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type IssueQuery struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssueQuery) Reset()         { *m = IssueQuery{} }
func (m *IssueQuery) String() string { return proto.CompactTextString(m) }
func (*IssueQuery) ProtoMessage()    {}
func (*IssueQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{13}
}

func (m *IssueQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueQuery.Unmarshal(m, b)
}
func (m *IssueQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueQuery.Marshal(b, m, deterministic)
}
func (m *IssueQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueQuery.Merge(m, src)
}
func (m *IssueQuery) XXX_Size() int {
	return xxx_messageInfo_IssueQuery.Size(m)
}
func (m *IssueQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueQuery.DiscardUnknown(m)
}

var xxx_messageInfo_IssueQuery proto.InternalMessageInfo

func (m *IssueQuery) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type Commit struct {
	SHA                  string   `protobuf:"bytes,1,opt,name=SHA,proto3" json:"SHA,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Auther               *User    `protobuf:"bytes,3,opt,name=auther,proto3" json:"auther,omitempty"`
	URL                  string   `protobuf:"bytes,4,opt,name=URL,proto3" json:"URL,omitempty"`
	Branch               string   `protobuf:"bytes,5,opt,name=branch,proto3" json:"branch,omitempty"`
	Committer            *User    `protobuf:"bytes,6,opt,name=committer,proto3" json:"committer,omitempty"`
	Org                  string   `protobuf:"bytes,8,opt,name=org,proto3" json:"org,omitempty"`
	Repo                 string   `protobuf:"bytes,9,opt,name=repo,proto3" json:"repo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{14}
}

func (m *Commit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit.Unmarshal(m, b)
}
func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit.Marshal(b, m, deterministic)
}
func (m *Commit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit.Merge(m, src)
}
func (m *Commit) XXX_Size() int {
	return xxx_messageInfo_Commit.Size(m)
}
func (m *Commit) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit.DiscardUnknown(m)
}

var xxx_messageInfo_Commit proto.InternalMessageInfo

func (m *Commit) GetSHA() string {
	if m != nil {
		return m.SHA
	}
	return ""
}

func (m *Commit) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Commit) GetAuther() *User {
	if m != nil {
		return m.Auther
	}
	return nil
}

func (m *Commit) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *Commit) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *Commit) GetCommitter() *User {
	if m != nil {
		return m.Committer
	}
	return nil
}

func (m *Commit) GetOrg() string {
	if m != nil {
		return m.Org
	}
	return ""
}

func (m *Commit) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

type CommitStatus struct {
	SHA                  string   `protobuf:"bytes,1,opt,name=SHA,proto3" json:"SHA,omitempty"`
	URL                  string   `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreateOn             string   `protobuf:"bytes,6,opt,name=CreateOn,proto3" json:"CreateOn,omitempty"`
	UpdatedOn            string   `protobuf:"bytes,7,opt,name=UpdatedOn,proto3" json:"UpdatedOn,omitempty"`
	Org                  string   `protobuf:"bytes,8,opt,name=org,proto3" json:"org,omitempty"`
	Repo                 string   `protobuf:"bytes,9,opt,name=repo,proto3" json:"repo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitStatus) Reset()         { *m = CommitStatus{} }
func (m *CommitStatus) String() string { return proto.CompactTextString(m) }
func (*CommitStatus) ProtoMessage()    {}
func (*CommitStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{15}
}

func (m *CommitStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitStatus.Unmarshal(m, b)
}
func (m *CommitStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitStatus.Marshal(b, m, deterministic)
}
func (m *CommitStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitStatus.Merge(m, src)
}
func (m *CommitStatus) XXX_Size() int {
	return xxx_messageInfo_CommitStatus.Size(m)
}
func (m *CommitStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitStatus.DiscardUnknown(m)
}

var xxx_messageInfo_CommitStatus proto.InternalMessageInfo

func (m *CommitStatus) GetSHA() string {
	if m != nil {
		return m.SHA
	}
	return ""
}

func (m *CommitStatus) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *CommitStatus) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *CommitStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CommitStatus) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CommitStatus) GetCreateOn() string {
	if m != nil {
		return m.CreateOn
	}
	return ""
}

func (m *CommitStatus) GetUpdatedOn() string {
	if m != nil {
		return m.UpdatedOn
	}
	return ""
}

func (m *CommitStatus) GetOrg() string {
	if m != nil {
		return m.Org
	}
	return ""
}

func (m *CommitStatus) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

type FileContent struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Encoding             string   `protobuf:"bytes,2,opt,name=Encoding,proto3" json:"Encoding,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Path                 string   `protobuf:"bytes,5,opt,name=Path,proto3" json:"Path,omitempty"`
	Content              string   `protobuf:"bytes,6,opt,name=Content,proto3" json:"Content,omitempty"`
	SHA                  string   `protobuf:"bytes,7,opt,name=SHA,proto3" json:"SHA,omitempty"`
	URL                  string   `protobuf:"bytes,8,opt,name=URL,proto3" json:"URL,omitempty"`
	GitURL               string   `protobuf:"bytes,9,opt,name=GitURL,proto3" json:"GitURL,omitempty"`
	HTMLURL              string   `protobuf:"bytes,10,opt,name=HTMLURL,proto3" json:"HTMLURL,omitempty"`
	DownloadURL          string   `protobuf:"bytes,11,opt,name=DownloadURL,proto3" json:"DownloadURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileContent) Reset()         { *m = FileContent{} }
func (m *FileContent) String() string { return proto.CompactTextString(m) }
func (*FileContent) ProtoMessage()    {}
func (*FileContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{16}
}

func (m *FileContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileContent.Unmarshal(m, b)
}
func (m *FileContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileContent.Marshal(b, m, deterministic)
}
func (m *FileContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileContent.Merge(m, src)
}
func (m *FileContent) XXX_Size() int {
	return xxx_messageInfo_FileContent.Size(m)
}
func (m *FileContent) XXX_DiscardUnknown() {
	xxx_messageInfo_FileContent.DiscardUnknown(m)
}

var xxx_messageInfo_FileContent proto.InternalMessageInfo

func (m *FileContent) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *FileContent) GetEncoding() string {
	if m != nil {
		return m.Encoding
	}
	return ""
}

func (m *FileContent) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileContent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileContent) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *FileContent) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *FileContent) GetSHA() string {
	if m != nil {
		return m.SHA
	}
	return ""
}

func (m *FileContent) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *FileContent) GetGitURL() string {
	if m != nil {
		return m.GitURL
	}
	return ""
}

func (m *FileContent) GetHTMLURL() string {
	if m != nil {
		return m.HTMLURL
	}
	return ""
}

func (m *FileContent) GetDownloadURL() string {
	if m != nil {
		return m.DownloadURL
	}
	return ""
}

type Issue struct {
	URL                  string   `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo                 string   `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo,omitempty"`
	Number               int64    `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	Key                  string   `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Title                string   `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	State                State    `protobuf:"varint,8,opt,name=state,proto3,enum=scallywag.State" json:"state,omitempty"`
	Label                []*Label `protobuf:"bytes,9,rep,name=label,proto3" json:"label,omitempty"`
	StatusesURL          string   `protobuf:"bytes,10,opt,name=StatusesURL,proto3" json:"StatusesURL,omitempty"`
	IssueURL             string   `protobuf:"bytes,11,opt,name=IssueURL,proto3" json:"IssueURL,omitempty"`
	CreatedAt            string   `protobuf:"bytes,12,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,13,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	ClosedAt             string   `protobuf:"bytes,14,opt,name=ClosedAt,proto3" json:"ClosedAt,omitempty"`
	IsPullRequest        bool     `protobuf:"varint,15,opt,name=IsPullRequest,proto3" json:"IsPullRequest,omitempty"`
	User                 *User    `protobuf:"bytes,16,opt,name=user,proto3" json:"user,omitempty"`
	ClosedBy             *User    `protobuf:"bytes,17,opt,name=ClosedBy,proto3" json:"ClosedBy,omitempty"`
	Assignees            []*User  `protobuf:"bytes,18,rep,name=assignees,proto3" json:"assignees,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Issue) Reset()         { *m = Issue{} }
func (m *Issue) String() string { return proto.CompactTextString(m) }
func (*Issue) ProtoMessage()    {}
func (*Issue) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{17}
}

func (m *Issue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Issue.Unmarshal(m, b)
}
func (m *Issue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Issue.Marshal(b, m, deterministic)
}
func (m *Issue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Issue.Merge(m, src)
}
func (m *Issue) XXX_Size() int {
	return xxx_messageInfo_Issue.Size(m)
}
func (m *Issue) XXX_DiscardUnknown() {
	xxx_messageInfo_Issue.DiscardUnknown(m)
}

var xxx_messageInfo_Issue proto.InternalMessageInfo

func (m *Issue) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *Issue) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Issue) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *Issue) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Issue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Issue) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Issue) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Issue) GetState() State {
	if m != nil {
		return m.State
	}
	return State_OPEN
}

func (m *Issue) GetLabel() []*Label {
	if m != nil {
		return m.Label
	}
	return nil
}

func (m *Issue) GetStatusesURL() string {
	if m != nil {
		return m.StatusesURL
	}
	return ""
}

func (m *Issue) GetIssueURL() string {
	if m != nil {
		return m.IssueURL
	}
	return ""
}

func (m *Issue) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Issue) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Issue) GetClosedAt() string {
	if m != nil {
		return m.ClosedAt
	}
	return ""
}

func (m *Issue) GetIsPullRequest() bool {
	if m != nil {
		return m.IsPullRequest
	}
	return false
}

func (m *Issue) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Issue) GetClosedBy() *User {
	if m != nil {
		return m.ClosedBy
	}
	return nil
}

func (m *Issue) GetAssignees() []*User {
	if m != nil {
		return m.Assignees
	}
	return nil
}

type Label struct {
	URL                  string   `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color                string   `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Label) Reset()         { *m = Label{} }
func (m *Label) String() string { return proto.CompactTextString(m) }
func (*Label) ProtoMessage()    {}
func (*Label) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{18}
}

func (m *Label) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Label.Unmarshal(m, b)
}
func (m *Label) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Label.Marshal(b, m, deterministic)
}
func (m *Label) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Label.Merge(m, src)
}
func (m *Label) XXX_Size() int {
	return xxx_messageInfo_Label.Size(m)
}
func (m *Label) XXX_DiscardUnknown() {
	xxx_messageInfo_Label.DiscardUnknown(m)
}

var xxx_messageInfo_Label proto.InternalMessageInfo

func (m *Label) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *Label) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Label) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

type IssueComment struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	HTMLURL              string   `protobuf:"bytes,2,opt,name=HTMLURL,proto3" json:"HTMLURL,omitempty"`
	User                 *User    `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,5,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssueComment) Reset()         { *m = IssueComment{} }
func (m *IssueComment) String() string { return proto.CompactTextString(m) }
func (*IssueComment) ProtoMessage()    {}
func (*IssueComment) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{19}
}

func (m *IssueComment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueComment.Unmarshal(m, b)
}
func (m *IssueComment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueComment.Marshal(b, m, deterministic)
}
func (m *IssueComment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueComment.Merge(m, src)
}
func (m *IssueComment) XXX_Size() int {
	return xxx_messageInfo_IssueComment.Size(m)
}
func (m *IssueComment) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueComment.DiscardUnknown(m)
}

var xxx_messageInfo_IssueComment proto.InternalMessageInfo

func (m *IssueComment) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *IssueComment) GetHTMLURL() string {
	if m != nil {
		return m.HTMLURL
	}
	return ""
}

func (m *IssueComment) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *IssueComment) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *IssueComment) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type Asset struct {
	DownloadURL          string   `protobuf:"bytes,1,opt,name=DownloadURL,proto3" json:"DownloadURL,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ContentType          string   `protobuf:"bytes,3,opt,name=contentType,proto3" json:"contentType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Asset) Reset()         { *m = Asset{} }
func (m *Asset) String() string { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()    {}
func (*Asset) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{20}
}

func (m *Asset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Asset.Unmarshal(m, b)
}
func (m *Asset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Asset.Marshal(b, m, deterministic)
}
func (m *Asset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asset.Merge(m, src)
}
func (m *Asset) XXX_Size() int {
	return xxx_messageInfo_Asset.Size(m)
}
func (m *Asset) XXX_DiscardUnknown() {
	xxx_messageInfo_Asset.DiscardUnknown(m)
}

var xxx_messageInfo_Asset proto.InternalMessageInfo

func (m *Asset) GetDownloadURL() string {
	if m != nil {
		return m.DownloadURL
	}
	return ""
}

func (m *Asset) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Asset) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

type Release struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TagName              string   `protobuf:"bytes,2,opt,name=tagName,proto3" json:"tagName,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	URL                  string   `protobuf:"bytes,4,opt,name=URL,proto3" json:"URL,omitempty"`
	HTMLURL              string   `protobuf:"bytes,5,opt,name=HTMLURL,proto3" json:"HTMLURL,omitempty"`
	DownloadCount        int64    `protobuf:"varint,6,opt,name=DownloadCount,proto3" json:"DownloadCount,omitempty"`
	Asset                []*Asset `protobuf:"bytes,7,rep,name=Asset,proto3" json:"Asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Release) Reset()         { *m = Release{} }
func (m *Release) String() string { return proto.CompactTextString(m) }
func (*Release) ProtoMessage()    {}
func (*Release) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{21}
}

func (m *Release) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Release.Unmarshal(m, b)
}
func (m *Release) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Release.Marshal(b, m, deterministic)
}
func (m *Release) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Release.Merge(m, src)
}
func (m *Release) XXX_Size() int {
	return xxx_messageInfo_Release.Size(m)
}
func (m *Release) XXX_DiscardUnknown() {
	xxx_messageInfo_Release.DiscardUnknown(m)
}

var xxx_messageInfo_Release proto.InternalMessageInfo

func (m *Release) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Release) GetTagName() string {
	if m != nil {
		return m.TagName
	}
	return ""
}

func (m *Release) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Release) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *Release) GetHTMLURL() string {
	if m != nil {
		return m.HTMLURL
	}
	return ""
}

func (m *Release) GetDownloadCount() int64 {
	if m != nil {
		return m.DownloadCount
	}
	return 0
}

func (m *Release) GetAsset() []*Asset {
	if m != nil {
		return m.Asset
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{22}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Organisation struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Organisation) Reset()         { *m = Organisation{} }
func (m *Organisation) String() string { return proto.CompactTextString(m) }
func (*Organisation) ProtoMessage()    {}
func (*Organisation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{23}
}

func (m *Organisation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Organisation.Unmarshal(m, b)
}
func (m *Organisation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Organisation.Marshal(b, m, deterministic)
}
func (m *Organisation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Organisation.Merge(m, src)
}
func (m *Organisation) XXX_Size() int {
	return xxx_messageInfo_Organisation.Size(m)
}
func (m *Organisation) XXX_DiscardUnknown() {
	xxx_messageInfo_Organisation.DiscardUnknown(m)
}

var xxx_messageInfo_Organisation proto.InternalMessageInfo

func (m *Organisation) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func init() {
	proto.RegisterEnum("scallywag.State", State_name, State_value)
	proto.RegisterType((*Confirmation)(nil), "scallywag.Confirmation")
	proto.RegisterType((*Provider)(nil), "scallywag.Provider")
	proto.RegisterType((*String)(nil), "scallywag.String")
	proto.RegisterType((*Branch)(nil), "scallywag.Branch")
	proto.RegisterType((*Collaborator)(nil), "scallywag.Collaborator")
	proto.RegisterType((*Repository)(nil), "scallywag.Repository")
	proto.RegisterType((*RepositoryInfo)(nil), "scallywag.RepositoryInfo")
	proto.RegisterType((*ForkInfo)(nil), "scallywag.ForkInfo")
	proto.RegisterType((*Organization)(nil), "scallywag.Organization")
	proto.RegisterType((*User)(nil), "scallywag.User")
	proto.RegisterType((*PullRequest)(nil), "scallywag.PullRequest")
	proto.RegisterType((*PullRequestComment)(nil), "scallywag.PullRequestComment")
	proto.RegisterType((*Webhook)(nil), "scallywag.Webhook")
	proto.RegisterType((*IssueQuery)(nil), "scallywag.IssueQuery")
	proto.RegisterType((*Commit)(nil), "scallywag.Commit")
	proto.RegisterType((*CommitStatus)(nil), "scallywag.CommitStatus")
	proto.RegisterType((*FileContent)(nil), "scallywag.FileContent")
	proto.RegisterType((*Issue)(nil), "scallywag.Issue")
	proto.RegisterType((*Label)(nil), "scallywag.Label")
	proto.RegisterType((*IssueComment)(nil), "scallywag.IssueComment")
	proto.RegisterType((*Asset)(nil), "scallywag.Asset")
	proto.RegisterType((*Release)(nil), "scallywag.Release")
	proto.RegisterType((*Empty)(nil), "scallywag.Empty")
	proto.RegisterType((*Organisation)(nil), "scallywag.Organisation")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 1342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0x5f, 0x6e, 0xdb, 0xc6,
	0x13, 0xfe, 0xd1, 0x14, 0xf5, 0x67, 0xe4, 0x28, 0xfa, 0x11, 0x6e, 0x40, 0x14, 0x69, 0x20, 0xb0,
	0x41, 0xea, 0xa6, 0x68, 0x1e, 0xd2, 0x13, 0x28, 0xb2, 0x53, 0x1b, 0x70, 0x2c, 0x97, 0x72, 0x50,
	0xa0, 0x2f, 0xc5, 0x4a, 0x5a, 0xcb, 0x84, 0x29, 0xae, 0xb2, 0xbb, 0xb2, 0xa1, 0x5c, 0xa0, 0x0f,
	0x3d, 0x43, 0xdf, 0x7a, 0x95, 0xde, 0xa2, 0x28, 0x7a, 0x8d, 0xbe, 0x15, 0x33, 0xbb, 0x4b, 0x52,
	0x16, 0x13, 0x04, 0xe8, 0xdb, 0xcc, 0x90, 0x9c, 0xdd, 0xf9, 0xe6, 0x9b, 0x6f, 0x97, 0xd0, 0xd5,
	0x9b, 0x15, 0x57, 0x2f, 0x56, 0x52, 0x68, 0x11, 0x76, 0xd4, 0x8c, 0x65, 0xd9, 0xe6, 0x8e, 0x2d,
	0xe2, 0x1e, 0xec, 0x8f, 0x44, 0x7e, 0x95, 0xca, 0x25, 0xd3, 0xa9, 0xc8, 0xe3, 0x9f, 0xa0, 0x7d,
	0x21, 0xc5, 0x6d, 0x3a, 0xe7, 0x32, 0x0c, 0xa1, 0x91, 0xb3, 0x25, 0x8f, 0xbc, 0x81, 0x77, 0xd8,
	0x49, 0xc8, 0x0e, 0xfb, 0xe0, 0xbf, 0x4d, 0xce, 0xa2, 0x3d, 0x0a, 0xa1, 0x19, 0x1e, 0x40, 0xa0,
	0xc5, 0x0d, 0xcf, 0x23, 0x9f, 0x62, 0xc6, 0xc1, 0x6f, 0x71, 0xc5, 0xa8, 0x61, 0xbe, 0x45, 0x3b,
	0x7e, 0x02, 0xcd, 0x89, 0x96, 0x69, 0xbe, 0xc0, 0x6f, 0x6e, 0x59, 0xb6, 0x76, 0xa9, 0x8d, 0x13,
	0xbf, 0x86, 0xe6, 0x2b, 0xc9, 0xf2, 0xd9, 0x35, 0x7e, 0x2d, 0xf9, 0x4a, 0xb8, 0x95, 0xd1, 0xc6,
	0x6f, 0xc4, 0x5d, 0xce, 0xa5, 0x5d, 0xdb, 0x38, 0xc5, 0x1e, 0xfd, 0x72, 0x8f, 0xf1, 0x09, 0xd6,
	0x94, 0x65, 0x6c, 0x2a, 0x24, 0xd3, 0x82, 0xde, 0x59, 0x2b, 0x2e, 0x5d, 0x36, 0xb4, 0x8b, 0x15,
	0xf6, 0x2a, 0x2b, 0xf4, 0xc1, 0x17, 0x72, 0x61, 0x53, 0xa1, 0x19, 0xff, 0xed, 0x01, 0x24, 0x7c,
	0x25, 0x54, 0xaa, 0x85, 0xdc, 0xd4, 0x02, 0x12, 0x41, 0xeb, 0xe4, 0xf2, 0xcd, 0x59, 0x09, 0x8a,
	0x73, 0xc3, 0x47, 0xd0, 0x9c, 0x4c, 0x4e, 0xf0, 0x81, 0xc9, 0x68, 0xbd, 0xf0, 0x73, 0x68, 0x8f,
	0x32, 0x91, 0x73, 0x7c, 0x62, 0xe0, 0x29, 0xfc, 0xf0, 0x39, 0xf4, 0x87, 0x59, 0x26, 0xee, 0xde,
	0x70, 0xb9, 0xe0, 0x23, 0xb1, 0x5c, 0xa6, 0x3a, 0x0a, 0x06, 0xde, 0x61, 0x3b, 0xd9, 0x89, 0x63,
	0x9e, 0x33, 0x96, 0x2f, 0xd6, 0x6c, 0xc1, 0xa3, 0xa6, 0xc9, 0xe3, 0x7c, 0xdc, 0xe9, 0x6b, 0x21,
	0x6f, 0xa2, 0x16, 0x7d, 0x4b, 0x36, 0x02, 0x38, 0xd1, 0x4c, 0xaa, 0xa8, 0x3d, 0xf0, 0x0e, 0xfd,
	0xc4, 0x38, 0xf1, 0x25, 0xf4, 0xca, 0x0a, 0x4f, 0xf3, 0xab, 0x02, 0x06, 0xaf, 0x80, 0xa1, 0x00,
	0x70, 0xaf, 0x02, 0xe0, 0x63, 0xe8, 0xa4, 0xea, 0x42, 0xa6, 0xb7, 0x4c, 0x1b, 0xf4, 0xdb, 0x49,
	0x19, 0x88, 0x7f, 0xf1, 0xa0, 0x8d, 0x8b, 0x52, 0xc2, 0xa7, 0xf0, 0x60, 0xbd, 0x52, 0x5a, 0x72,
	0xb6, 0x1c, 0x53, 0x07, 0x4d, 0xea, 0xed, 0x20, 0x96, 0x3e, 0xe7, 0x4a, 0xa7, 0x39, 0x11, 0x71,
	0x5c, 0x69, 0xf5, 0x4e, 0x3c, 0xfc, 0xda, 0x76, 0x0f, 0xd7, 0xed, 0xbe, 0xfc, 0xec, 0x45, 0xc1,
	0xe7, 0x17, 0x65, 0x2d, 0xa6, 0xa9, 0x71, 0x0c, 0xfb, 0x63, 0xb9, 0x60, 0x79, 0xfa, 0x9e, 0xbe,
	0xaf, 0xeb, 0x61, 0x7c, 0x0b, 0x8d, 0xb7, 0x58, 0xd3, 0x01, 0x04, 0x99, 0x58, 0xa4, 0xb9, 0xa3,
	0x25, 0x39, 0x18, 0xe5, 0x4b, 0x96, 0x66, 0x8e, 0x78, 0xe4, 0xd4, 0x11, 0xcf, 0x0d, 0x47, 0xa3,
	0x1c, 0x8e, 0xc7, 0xd0, 0x19, 0xde, 0x32, 0xcd, 0x24, 0xc6, 0x03, 0x8a, 0x97, 0x81, 0xf8, 0x1f,
	0x1f, 0xba, 0x17, 0xeb, 0x2c, 0x4b, 0xf8, 0xbb, 0x35, 0x57, 0x1a, 0x73, 0xbe, 0x62, 0xaa, 0xd8,
	0x1b, 0xda, 0x18, 0x3b, 0xe1, 0x6c, 0xee, 0xb0, 0x47, 0xdb, 0xad, 0xe3, 0x97, 0xeb, 0x3c, 0xa9,
	0xf2, 0xd4, 0x6e, 0xa0, 0xca, 0xdc, 0x03, 0x08, 0x0c, 0xa2, 0x66, 0x0f, 0xc6, 0x41, 0x86, 0x9e,
	0xaf, 0x97, 0x53, 0x2e, 0x89, 0x3f, 0x7e, 0x62, 0x3d, 0xdc, 0x35, 0x11, 0x8d, 0x4d, 0x33, 0x6e,
	0x29, 0x54, 0x06, 0xf0, 0x2b, 0x72, 0xe6, 0x44, 0xa4, 0x76, 0x62, 0xbd, 0xf0, 0x19, 0xf1, 0x4b,
	0xf3, 0xa8, 0x33, 0xf0, 0x0e, 0x7b, 0x2f, 0xfb, 0x95, 0xae, 0x50, 0x3c, 0x31, 0x8f, 0xc3, 0x01,
	0x74, 0xd1, 0x58, 0x2b, 0xae, 0xb0, 0x0a, 0xa0, 0x1d, 0x55, 0x43, 0xc8, 0xec, 0x53, 0xa5, 0xd6,
	0x34, 0x21, 0x5d, 0xc3, 0x6c, 0xe7, 0xe3, 0xbc, 0x1d, 0xa5, 0x57, 0x57, 0xf8, 0x68, 0xdf, 0xcc,
	0x9b, 0x75, 0xc3, 0x67, 0xd0, 0xab, 0x8c, 0xc7, 0xe4, 0x64, 0x18, 0x3d, 0xa0, 0x17, 0xee, 0x45,
	0x31, 0xc3, 0x28, 0x13, 0x8a, 0x0f, 0x75, 0xd4, 0x33, 0x19, 0xac, 0x8b, 0xeb, 0x9a, 0x5a, 0x86,
	0x3a, 0x7a, 0x68, 0xd6, 0x75, 0x3e, 0x92, 0xf8, 0x8c, 0x29, 0x6d, 0xd3, 0x5c, 0xb3, 0xa8, 0x6f,
	0x48, 0xbc, 0x15, 0x44, 0x9c, 0x2f, 0x53, 0x9d, 0xf1, 0xe8, 0xff, 0x06, 0x67, 0x72, 0xa8, 0xaf,
	0x62, 0xbe, 0x89, 0x42, 0xdb, 0x57, 0x31, 0xdf, 0xc4, 0x07, 0x10, 0x56, 0x5a, 0x8f, 0x19, 0x78,
	0xae, 0xe3, 0x25, 0xb4, 0x7e, 0xe4, 0xd3, 0x6b, 0x21, 0x6e, 0xc2, 0x1e, 0xec, 0x9d, 0x1e, 0x11,
	0x15, 0xfc, 0x64, 0xef, 0xf4, 0xe8, 0xc3, 0xfa, 0x57, 0x4c, 0x42, 0x45, 0xc7, 0xee, 0xd1, 0xf0,
	0x11, 0x34, 0x15, 0x9f, 0x49, 0xae, 0x6d, 0xff, 0xad, 0x17, 0xc7, 0x00, 0x04, 0xec, 0x0f, 0x6b,
	0x6e, 0x48, 0xf2, 0x0e, 0x0d, 0x47, 0x7f, 0x72, 0xe2, 0x3f, 0x3d, 0x68, 0x5a, 0xc5, 0xe9, 0x83,
	0x8f, 0xb0, 0x5a, 0x65, 0xb0, 0x58, 0x2e, 0xb9, 0x52, 0x28, 0x41, 0x56, 0xfd, 0xac, 0x1b, 0x7e,
	0x05, 0x4d, 0xb6, 0xd6, 0xd7, 0x5c, 0xda, 0x21, 0x7d, 0x58, 0xa1, 0x03, 0x0e, 0x5b, 0x62, 0x1f,
	0xd7, 0xef, 0x76, 0x4a, 0xe7, 0x80, 0xdb, 0xad, 0xf1, 0xc2, 0x6f, 0xa1, 0x33, 0xa3, 0x8d, 0x68,
	0xcb, 0xd8, 0x9a, 0xac, 0xe5, 0x1b, 0x4e, 0xc7, 0xda, 0x5b, 0x3a, 0x46, 0x60, 0x75, 0x4a, 0xb0,
	0xe2, 0xbf, 0x3c, 0x3c, 0x2d, 0xa8, 0x7f, 0xc4, 0xc0, 0x9a, 0x22, 0x6b, 0xcf, 0x3c, 0xa5, 0x9d,
	0xf0, 0x75, 0x12, 0xe3, 0x14, 0x92, 0xd0, 0xa8, 0x48, 0xc2, 0x00, 0xba, 0x73, 0xae, 0x66, 0x32,
	0x5d, 0xa1, 0xfa, 0xd8, 0x82, 0xaa, 0x21, 0x3a, 0x0e, 0x24, 0x67, 0x9a, 0x8f, 0x73, 0x27, 0xe3,
	0xce, 0xc7, 0x41, 0x7c, 0xbb, 0x9a, 0x33, 0xcd, 0xe7, 0xe3, 0x9c, 0x06, 0xb1, 0x93, 0x94, 0x81,
	0x4f, 0x2c, 0xf0, 0xd7, 0x3d, 0xe8, 0xbe, 0x4e, 0x33, 0x3e, 0x12, 0xb9, 0xe6, 0x39, 0x89, 0xcc,
	0x25, 0x9e, 0xcc, 0x56, 0x64, 0xd0, 0xc6, 0x3d, 0x1c, 0xe7, 0x33, 0x31, 0x4f, 0xf3, 0x85, 0x2d,
	0xb3, 0xf0, 0xf1, 0xfd, 0x49, 0xfa, 0xde, 0x94, 0xea, 0x27, 0x64, 0x63, 0xec, 0xbc, 0x52, 0x29,
	0xda, 0x18, 0xbb, 0x60, 0xda, 0xf5, 0x8c, 0x6c, 0x1a, 0x35, 0xb3, 0xac, 0x2d, 0xcd, 0xb9, 0x0e,
	0xe5, 0xd6, 0x0e, 0xca, 0xed, 0x2d, 0x1e, 0x7c, 0x9f, 0x6a, 0x0c, 0x9a, 0x7a, 0xac, 0x57, 0x3d,
	0x72, 0x61, 0xfb, 0xc8, 0x1d, 0x40, 0xf7, 0x48, 0xdc, 0xe5, 0x99, 0x60, 0xf3, 0x52, 0x3b, 0xaa,
	0xa1, 0xf8, 0xf7, 0x06, 0x04, 0x44, 0x79, 0xb7, 0x9e, 0xb7, 0xd5, 0xd5, 0x4f, 0x9c, 0xb0, 0x47,
	0xd0, 0xcc, 0x8d, 0x70, 0x36, 0x8c, 0x70, 0x1a, 0x0f, 0x73, 0xde, 0xf0, 0x8d, 0x85, 0x00, 0x4d,
	0xba, 0x1d, 0x91, 0x20, 0x34, 0xed, 0xed, 0xc8, 0x09, 0xc2, 0x14, 0x05, 0xc1, 0x94, 0x4f, 0x36,
	0xca, 0xa7, 0xe1, 0x54, 0xfb, 0x43, 0xf2, 0x69, 0x58, 0xf6, 0x0c, 0x82, 0x8c, 0x4d, 0x79, 0x16,
	0x75, 0x06, 0xfe, 0x61, 0x77, 0xeb, 0xbd, 0x33, 0x8c, 0x27, 0xe6, 0xf1, 0x7f, 0x94, 0xd9, 0xc7,
	0xd0, 0x31, 0x2c, 0x44, 0x2d, 0x34, 0x42, 0x5b, 0x06, 0x2a, 0xbc, 0x1c, 0x6a, 0xab, 0xb2, 0x65,
	0xc0, 0x5e, 0x70, 0x14, 0x3d, 0xec, 0x15, 0x17, 0x1c, 0xe5, 0x64, 0xf4, 0x54, 0x55, 0x84, 0x8f,
	0x74, 0xb6, 0x9d, 0x6c, 0x07, 0xc3, 0x2f, 0xed, 0x85, 0xa3, 0x5f, 0x3f, 0xe4, 0xe6, 0x06, 0xf2,
	0x8d, 0x5b, 0xe6, 0xd5, 0x86, 0xe4, 0xb6, 0xe6, 0xc5, 0xe2, 0x05, 0xd4, 0x0e, 0xa6, 0x54, 0xba,
	0xc8, 0x39, 0x57, 0x51, 0x48, 0xc8, 0xed, 0x6a, 0x47, 0xf1, 0x46, 0x3c, 0x82, 0x80, 0xc0, 0xac,
	0x61, 0x89, 0x9b, 0xf2, 0xbd, 0xca, 0x94, 0x1f, 0x40, 0x30, 0x13, 0x99, 0x90, 0x4e, 0x0f, 0xc8,
	0x89, 0x7f, 0xf3, 0x60, 0x9f, 0x00, 0xb5, 0xea, 0x5e, 0xb4, 0xdd, 0xab, 0xb4, 0xfd, 0xc3, 0xf7,
	0x47, 0x07, 0x82, 0xff, 0x31, 0x10, 0xb6, 0xfa, 0xd4, 0xf8, 0x68, 0x9f, 0x82, 0x7b, 0x7d, 0x8a,
	0x7f, 0x86, 0x60, 0xa8, 0x14, 0xd7, 0xf7, 0xc7, 0xc6, 0xdb, 0x19, 0x9b, 0xda, 0xa2, 0x07, 0xd0,
	0x9d, 0x99, 0x69, 0x26, 0x3d, 0x31, 0xa5, 0x57, 0x43, 0xf1, 0x1f, 0x1e, 0xb4, 0x12, 0x9e, 0x71,
	0x7b, 0x8f, 0xa9, 0xbb, 0x3b, 0x6b, 0xb6, 0x38, 0x2f, 0x13, 0x3b, 0xb7, 0x40, 0xca, 0xaf, 0x20,
	0xb5, 0x7b, 0x50, 0x54, 0xb0, 0x0b, 0xb6, 0xb1, 0x7b, 0x0a, 0x0f, 0xdc, 0xf6, 0x47, 0x62, 0x6d,
	0xe5, 0xc7, 0x4f, 0xb6, 0x83, 0x38, 0x4a, 0x04, 0x40, 0xd4, 0xda, 0x19, 0x25, 0x8a, 0x27, 0xe6,
	0x71, 0xdc, 0x82, 0xe0, 0x78, 0xb9, 0xd2, 0x9b, 0xf8, 0xa9, 0xbb, 0x4c, 0x2a, 0x73, 0x99, 0xac,
	0xbd, 0x30, 0x3e, 0xff, 0xc2, 0x5e, 0x84, 0xc2, 0x36, 0x34, 0xc6, 0x17, 0xc7, 0xe7, 0xfd, 0xff,
	0x85, 0x00, 0xcd, 0xd1, 0xd9, 0x78, 0x72, 0x7c, 0xd4, 0xf7, 0xa6, 0x4d, 0xfa, 0x09, 0xfb, 0xee,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x21, 0x10, 0x62, 0x93, 0x0d, 0x00, 0x00,
}
