// Code generated by protoc-gen-go. DO NOT EDIT.
// source: webhook.proto

package scallywag

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

func init() { proto.RegisterFile("webhook.proto", fileDescriptor_webhook_83775e53ec33d3b0) }

var fileDescriptor_webhook_83775e53ec33d3b0 = []byte{
	// 55 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4f, 0x4d, 0xca,
	0xc8, 0xcf, 0xcf, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2c, 0x4e, 0x4e, 0xcc, 0xc9,
	0xa9, 0x2c, 0x4f, 0x4c, 0x4f, 0x62, 0x03, 0x8b, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x39,
	0x99, 0xde, 0xdf, 0x22, 0x00, 0x00, 0x00,
}
